pandas repo를 샘플로 데이터 구조 파악

In [2]:
import os
import time
import requests
import pandas as pd
from datetime import datetime, timezone
from dotenv import load_dotenv

load_dotenv()
token = os.getenv("GITHUB_TOKEN")
HEADERS={
    "Accept": "application/vnd.github+json"
}
if token:
    HEADERS["Authorization"]=f"Bearer {token}"
BASE_URL = "https://api.github.com"
FULL_NAME = "pandas-dev/pandas"
repo_url = f"{BASE_URL}/repos/{FULL_NAME}"

In [3]:
def fetch_json(url, params=None, headers=HEADERS, sleep_sec=0.2):
    res = requests.get(url, headers=headers, params=params)
    res.raise_for_status()
    time.sleep(sleep_sec)
    return res.json()

In [73]:
repo_data = fetch_json(repo_url)
repo_data

{'id': 858127,
 'node_id': 'MDEwOlJlcG9zaXRvcnk4NTgxMjc=',
 'name': 'pandas',
 'full_name': 'pandas-dev/pandas',
 'private': False,
 'owner': {'login': 'pandas-dev',
  'id': 21206976,
  'node_id': 'MDEyOk9yZ2FuaXphdGlvbjIxMjA2OTc2',
  'avatar_url': 'https://avatars.githubusercontent.com/u/21206976?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/pandas-dev',
  'html_url': 'https://github.com/pandas-dev',
  'followers_url': 'https://api.github.com/users/pandas-dev/followers',
  'following_url': 'https://api.github.com/users/pandas-dev/following{/other_user}',
  'gists_url': 'https://api.github.com/users/pandas-dev/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/pandas-dev/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/pandas-dev/subscriptions',
  'organizations_url': 'https://api.github.com/users/pandas-dev/orgs',
  'repos_url': 'https://api.github.com/users/pandas-dev/repos',
  'events_url': 'https://api.github.com/users/pandas-dev/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/pandas-dev/received_events',
  'type': 'Organization',
  'user_view_type': 'public',
  'site_admin': False},
 'html_url': 'https://github.com/pandas-dev/pandas',
 'description': 'Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more',
 'fork': False,
 'url': 'https://api.github.com/repos/pandas-dev/pandas',
 'forks_url': 'https://api.github.com/repos/pandas-dev/pandas/forks',
 'keys_url': 'https://api.github.com/repos/pandas-dev/pandas/keys{/key_id}',
 'collaborators_url': 'https://api.github.com/repos/pandas-dev/pandas/collaborators{/collaborator}',
 'teams_url': 'https://api.github.com/repos/pandas-dev/pandas/teams',
 'hooks_url': 'https://api.github.com/repos/pandas-dev/pandas/hooks',
 'issue_events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/events{/number}',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/events',
 'assignees_url': 'https://api.github.com/repos/pandas-dev/pandas/assignees{/user}',
 'branches_url': 'https://api.github.com/repos/pandas-dev/pandas/branches{/branch}',
 'tags_url': 'https://api.github.com/repos/pandas-dev/pandas/tags',
 'blobs_url': 'https://api.github.com/repos/pandas-dev/pandas/git/blobs{/sha}',
 'git_tags_url': 'https://api.github.com/repos/pandas-dev/pandas/git/tags{/sha}',
 'git_refs_url': 'https://api.github.com/repos/pandas-dev/pandas/git/refs{/sha}',
 'trees_url': 'https://api.github.com/repos/pandas-dev/pandas/git/trees{/sha}',
 'statuses_url': 'https://api.github.com/repos/pandas-dev/pandas/statuses/{sha}',
 'languages_url': 'https://api.github.com/repos/pandas-dev/pandas/languages',
 'stargazers_url': 'https://api.github.com/repos/pandas-dev/pandas/stargazers',
 'contributors_url': 'https://api.github.com/repos/pandas-dev/pandas/contributors',
 'subscribers_url': 'https://api.github.com/repos/pandas-dev/pandas/subscribers',
 'subscription_url': 'https://api.github.com/repos/pandas-dev/pandas/subscription',
 'commits_url': 'https://api.github.com/repos/pandas-dev/pandas/commits{/sha}',
 'git_commits_url': 'https://api.github.com/repos/pandas-dev/pandas/git/commits{/sha}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/comments{/number}',
 'issue_comment_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/comments{/number}',
 'contents_url': 'https://api.github.com/repos/pandas-dev/pandas/contents/{+path}',
 'compare_url': 'https://api.github.com/repos/pandas-dev/pandas/compare/{base}...{head}',
 'merges_url': 'https://api.github.com/repos/pandas-dev/pandas/merges',
 'archive_url': 'https://api.github.com/repos/pandas-dev/pandas/{archive_format}{/ref}',
 'downloads_url': 'https://api.github.com/repos/pandas-dev/pandas/downloads',
 'issues_url': 'https://api.github.com/repos/pandas-dev/pandas/issues{/number}',
 'pulls_url': 'https://api.github.com/repos/pandas-dev/pandas/pulls{/number}',
 'milestones_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones{/number}',
 'notifications_url': 'https://api.github.com/repos/pandas-dev/pandas/notifications{?since,all,participating}',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/labels{/name}',
 'releases_url': 'https://api.github.com/repos/pandas-dev/pandas/releases{/id}',
 'deployments_url': 'https://api.github.com/repos/pandas-dev/pandas/deployments',
 'created_at': '2010-08-24T01:37:33Z',
 'updated_at': '2026-04-03T02:14:17Z',
 'pushed_at': '2026-04-03T00:25:12Z',
 'git_url': 'git://github.com/pandas-dev/pandas.git',
 'ssh_url': 'git@github.com:pandas-dev/pandas.git',
 'clone_url': 'https://github.com/pandas-dev/pandas.git',
 'svn_url': 'https://github.com/pandas-dev/pandas',
 'homepage': 'https://pandas.pydata.org',
 'size': 387923,
 'stargazers_count': 48331,
 'watchers_count': 48331,
 'language': 'Python',
 'has_issues': True,
 'has_projects': True,
 'has_downloads': True,
 'has_wiki': False,
 'has_pages': False,
 'has_discussions': False,
 'forks_count': 19818,
 'mirror_url': None,
 'archived': False,
 'disabled': False,
 'open_issues_count': 3504,
 'license': {'key': 'bsd-3-clause',
  'name': 'BSD 3-Clause "New" or "Revised" License',
  'spdx_id': 'BSD-3-Clause',
  'url': 'https://api.github.com/licenses/bsd-3-clause',
  'node_id': 'MDc6TGljZW5zZTU='},
 'allow_forking': True,
 'is_template': False,
 'web_commit_signoff_required': False,
 'has_pull_requests': True,
 'pull_request_creation_policy': 'all',
 'topics': ['alignment',
  'data-analysis',
  'data-science',
  'flexible',
  'pandas',
  'python'],
 'visibility': 'public',
 'forks': 19818,
 'open_issues': 3504,
 'watchers': 48331,
 'default_branch': 'main',
 'permissions': {'admin': False,
  'maintain': False,
  'push': False,
  'triage': False,
  'pull': True},
 'temp_clone_token': '',
 'custom_properties': {},
 'organization': {'login': 'pandas-dev',
  'id': 21206976,
  'node_id': 'MDEyOk9yZ2FuaXphdGlvbjIxMjA2OTc2',
  'avatar_url': 'https://avatars.githubusercontent.com/u/21206976?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/pandas-dev',
  'html_url': 'https://github.com/pandas-dev',
  'followers_url': 'https://api.github.com/users/pandas-dev/followers',
  'following_url': 'https://api.github.com/users/pandas-dev/following{/other_user}',
  'gists_url': 'https://api.github.com/users/pandas-dev/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/pandas-dev/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/pandas-dev/subscriptions',
  'organizations_url': 'https://api.github.com/users/pandas-dev/orgs',
  'repos_url': 'https://api.github.com/users/pandas-dev/repos',
  'events_url': 'https://api.github.com/users/pandas-dev/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/pandas-dev/received_events',
  'type': 'Organization',
  'user_view_type': 'public',
  'site_admin': False},
 'network_count': 19818,
 'subscribers_count': 1105}

In [74]:
selected_keys = [

    # 기본 정보
    "fork",
    "html_url",
    "homepage",


    # 시간
    "created_at",
    "updated_at",
    "pushed_at",

    # 인기 / 규모
    "size",
    "stargazers_count",
    "forks_count",
    "subscribers_count",
    "open_issues_count",
    "network_count",

    # 상태 / 운영
    "has_issues",
    "has_projects",
    "has_downloads",
    "has_wiki",
    "has_pages",
    "has_discussions",
    "archived",
    "disabled",
    "allow_forking",
    "has_pull_requests",

    # nested (flatten 대상)
    "owner.login",
    "owner.type",
    "license.key",
    "license.name",
    "license.spdx_id",
    "organization.login",
    "organization.type",

    # endpoint (확장 수집용)
    "contributors_url",
    "commits_url",
    "issues_url",
    "issue_comment_url",
    "pulls_url",
    "releases_url",
    "languages_url",
    "branches_url",
    "tags_url",
    "events_url",
    "issue_events_url",
    "comments_url",
    "labels_url",
    "milestones_url",
    "deployments_url",
    "stargazers_url",
    "subscribers_url",
]

In [75]:
filtered_repo = {k: repo_data[k] for k in selected_keys if k in repo_data}
filtered_repo

{'fork': False,
 'html_url': 'https://github.com/pandas-dev/pandas',
 'homepage': 'https://pandas.pydata.org',
 'created_at': '2010-08-24T01:37:33Z',
 'updated_at': '2026-04-03T02:14:17Z',
 'pushed_at': '2026-04-03T00:25:12Z',
 'size': 387923,
 'stargazers_count': 48331,
 'forks_count': 19818,
 'subscribers_count': 1105,
 'open_issues_count': 3504,
 'network_count': 19818,
 'has_issues': True,
 'has_projects': True,
 'has_downloads': True,
 'has_wiki': False,
 'has_pages': False,
 'has_discussions': False,
 'archived': False,
 'disabled': False,
 'allow_forking': True,
 'has_pull_requests': True,
 'contributors_url': 'https://api.github.com/repos/pandas-dev/pandas/contributors',
 'commits_url': 'https://api.github.com/repos/pandas-dev/pandas/commits{/sha}',
 'issues_url': 'https://api.github.com/repos/pandas-dev/pandas/issues{/number}',
 'issue_comment_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/comments{/number}',
 'pulls_url': 'https://api.github.com/repos/pandas-dev/pandas/pulls{/number}',
 'releases_url': 'https://api.github.com/repos/pandas-dev/pandas/releases{/id}',
 'languages_url': 'https://api.github.com/repos/pandas-dev/pandas/languages',
 'branches_url': 'https://api.github.com/repos/pandas-dev/pandas/branches{/branch}',
 'tags_url': 'https://api.github.com/repos/pandas-dev/pandas/tags',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/events',
 'issue_events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/events{/number}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/comments{/number}',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/labels{/name}',
 'milestones_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones{/number}',
 'deployments_url': 'https://api.github.com/repos/pandas-dev/pandas/deployments',
 'stargazers_url': 'https://api.github.com/repos/pandas-dev/pandas/stargazers',
 'subscribers_url': 'https://api.github.com/repos/pandas-dev/pandas/subscribers'}

In [76]:
raw_key = {k: v for k, v in filtered_repo.items()
           if not (isinstance(v, str) and "http" in v)}

In [77]:
raw_key

{'fork': False,
 'created_at': '2010-08-24T01:37:33Z',
 'updated_at': '2026-04-03T02:14:17Z',
 'pushed_at': '2026-04-03T00:25:12Z',
 'size': 387923,
 'stargazers_count': 48331,
 'forks_count': 19818,
 'subscribers_count': 1105,
 'open_issues_count': 3504,
 'network_count': 19818,
 'has_issues': True,
 'has_projects': True,
 'has_downloads': True,
 'has_wiki': False,
 'has_pages': False,
 'has_discussions': False,
 'archived': False,
 'disabled': False,
 'allow_forking': True,
 'has_pull_requests': True}

In [78]:
url_key = {k: v for k, v in filtered_repo.items()
           if (isinstance(v, str) and "http" in v)}
url_key

{'html_url': 'https://github.com/pandas-dev/pandas',
 'homepage': 'https://pandas.pydata.org',
 'contributors_url': 'https://api.github.com/repos/pandas-dev/pandas/contributors',
 'commits_url': 'https://api.github.com/repos/pandas-dev/pandas/commits{/sha}',
 'issues_url': 'https://api.github.com/repos/pandas-dev/pandas/issues{/number}',
 'issue_comment_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/comments{/number}',
 'pulls_url': 'https://api.github.com/repos/pandas-dev/pandas/pulls{/number}',
 'releases_url': 'https://api.github.com/repos/pandas-dev/pandas/releases{/id}',
 'languages_url': 'https://api.github.com/repos/pandas-dev/pandas/languages',
 'branches_url': 'https://api.github.com/repos/pandas-dev/pandas/branches{/branch}',
 'tags_url': 'https://api.github.com/repos/pandas-dev/pandas/tags',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/events',
 'issue_events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/events{/number}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/comments{/number}',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/labels{/name}',
 'milestones_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones{/number}',
 'deployments_url': 'https://api.github.com/repos/pandas-dev/pandas/deployments',
 'stargazers_url': 'https://api.github.com/repos/pandas-dev/pandas/stargazers',
 'subscribers_url': 'https://api.github.com/repos/pandas-dev/pandas/subscribers'}

JSON 문자열 → Python dict/list로 파싱됨 → 구조 기반 순회

In [94]:
from pathlib import Path

def is_github_api_url(value):
    return isinstance(value, str) and value.startswith("https://api.github.com/")

def is_template_url(value):
    return isinstance(value, str) and ("{" in value and "}" in value)

def save_progress(rows, error_log, save_prefix="walk_json_progress"):
    pd.DataFrame(rows).to_csv(f"{save_prefix}_rows.csv", index=False)
    pd.DataFrame(error_log).to_csv(f"{save_prefix}_errors.csv", index=False)

def walk_json(
    obj,
    parent_path="",
    depth=0,
    max_depth=1,
    visited_urls=None,
    error_log=None,
    rows=None,
    verbose=True,
    save_every=100,
    counter=None,
    save_prefix="walk_json_progress"
):
    if visited_urls is None:
        visited_urls = set()
    if error_log is None:
        error_log = []
    if rows is None:
        rows = []
    if counter is None:
        counter = {"n": 0}

    # depth 제한
    if depth > max_depth:
        return rows, error_log

    def append_row(row):
        rows.append(row)
        counter["n"] += 1

        if save_every and counter["n"] % save_every == 0:
            save_progress(rows, error_log, save_prefix)
            if verbose:
                print(f"[checkpoint] saved {counter['n']} rows")

    if isinstance(obj, dict):
        for key, value in obj.items():
            current_path = f"{parent_path}.{key}" if parent_path else key

            append_row({
                "path": current_path,
                "key": key,
                "dtype": type(value).__name__,
                "example_value": str(value)[:120],
                "is_github_api_url": is_github_api_url(value),
                "fetch_status": None,
                "error_message": None,
                "depth": depth,
            })

            if isinstance(value, (dict, list)):
                walk_json(
                    value,
                    parent_path=current_path,
                    depth=depth + 1,
                    max_depth=max_depth,
                    visited_urls=visited_urls,
                    error_log=error_log,
                    rows=rows,
                    verbose=verbose,
                    save_every=save_every,
                    counter=counter,
                    save_prefix=save_prefix
                )

            elif (
                depth < max_depth
                and is_github_api_url(value)
                and not is_template_url(value)
                and value not in visited_urls
            ):
                visited_urls.add(value)

                try:
                    sub_data = fetch_json(value)

                    append_row({
                        "path": current_path + ".__api_fetch__",
                        "key": "__api_fetch__",
                        "dtype": type(sub_data).__name__,
                        "example_value": str(value)[:120],
                        "is_github_api_url": True,
                        "fetch_status": "success",
                        "error_message": None,
                        "depth": depth,
                    })

                    if sub_data is not None:
                        walk_json(
                            sub_data,
                            parent_path=current_path + ".__api__",
                            depth=depth + 1,
                            max_depth=max_depth,
                            visited_urls=visited_urls,
                            error_log=error_log,
                            rows=rows,
                            verbose=verbose,
                            save_every=save_every,
                            counter=counter,
                            save_prefix=save_prefix
                        )

                except requests.exceptions.HTTPError as e:
                    msg = f"HTTPError: {e}"
                    error_log.append({
                        "path": current_path,
                        "url": value,
                        "error_type": "HTTPError",
                        "error_message": str(e),
                        "depth": depth,
                    })

                    append_row({
                        "path": current_path + ".__api_error__",
                        "key": "__api_error__",
                        "dtype": "error",
                        "example_value": str(value)[:120],
                        "is_github_api_url": True,
                        "fetch_status": "failed",
                        "error_message": msg,
                        "depth": depth,
                    })

                    if verbose:
                        print(f"[HTTPError] {current_path} -> {value}")
                        print(f"  {e}")

                except Exception as e:
                    msg = f"{type(e).__name__}: {e}"
                    error_log.append({
                        "path": current_path,
                        "url": value,
                        "error_type": type(e).__name__,
                        "error_message": str(e),
                        "depth": depth,
                    })

                    append_row({
                        "path": current_path + ".__api_error__",
                        "key": "__api_error__",
                        "dtype": "error",
                        "example_value": str(value)[:120],
                        "is_github_api_url": True,
                        "fetch_status": "failed",
                        "error_message": msg,
                        "depth": depth,
                    })

                    if verbose:
                        print(f"[Error] {current_path} -> {value}")
                        print(f"  {msg}")

    elif isinstance(obj, list):
        for idx, item in enumerate(obj):
            current_path = f"{parent_path}[{idx}]"

            append_row({
                "path": current_path,
                "key": f"[{idx}]",
                "dtype": type(item).__name__,
                "example_value": str(item)[:120],
                "is_github_api_url": is_github_api_url(item),
                "fetch_status": None,
                "error_message": None,
                "depth": depth,
            })

            if isinstance(item, (dict, list)):
                walk_json(
                    item,
                    parent_path=current_path,
                    depth=depth + 1,
                    max_depth=max_depth,
                    visited_urls=visited_urls,
                    error_log=error_log,
                    rows=rows,
                    verbose=verbose,
                    save_every=save_every,
                    counter=counter,
                    save_prefix=save_prefix
                )

            elif (
                depth < max_depth
                and is_github_api_url(item)
                and not is_template_url(item)
                and item not in visited_urls
            ):
                visited_urls.add(item)

                try:
                    sub_data = fetch_json(item)

                    append_row({
                        "path": current_path + ".__api_fetch__",
                        "key": "__api_fetch__",
                        "dtype": type(sub_data).__name__,
                        "example_value": str(item)[:120],
                        "is_github_api_url": True,
                        "fetch_status": "success",
                        "error_message": None,
                        "depth": depth,
                    })

                    if sub_data is not None:
                        walk_json(
                            sub_data,
                            parent_path=current_path + ".__api__",
                            depth=depth + 1,
                            max_depth=max_depth,
                            visited_urls=visited_urls,
                            error_log=error_log,
                            rows=rows,
                            verbose=verbose,
                            save_every=save_every,
                            counter=counter,
                            save_prefix=save_prefix
                        )

                except requests.exceptions.HTTPError as e:
                    msg = f"HTTPError: {e}"
                    error_log.append({
                        "path": current_path,
                        "url": item,
                        "error_type": "HTTPError",
                        "error_message": str(e),
                        "depth": depth,
                    })

                    append_row({
                        "path": current_path + ".__api_error__",
                        "key": "__api_error__",
                        "dtype": "error",
                        "example_value": str(item)[:120],
                        "is_github_api_url": True,
                        "fetch_status": "failed",
                        "error_message": msg,
                        "depth": depth,
                    })

                    if verbose:
                        print(f"[HTTPError] {current_path} -> {item}")
                        print(f"  {e}")

                except Exception as e:
                    msg = f"{type(e).__name__}: {e}"
                    error_log.append({
                        "path": current_path,
                        "url": item,
                        "error_type": type(e).__name__,
                        "error_message": str(e),
                        "depth": depth,
                    })

                    append_row({
                        "path": current_path + ".__api_error__",
                        "key": "__api_error__",
                        "dtype": "error",
                        "example_value": str(item)[:120],
                        "is_github_api_url": True,
                        "fetch_status": "failed",
                        "error_message": msg,
                        "depth": depth,
                    })

                    if verbose:
                        print(f"[Error] {current_path} -> {item}")
                        print(f"  {msg}")

    # 마지막에도 저장
    if depth == 0:
        save_progress(rows, error_log, save_prefix)
        if verbose:
            print(f"[done] total rows={len(rows)}, total errors={len(error_log)}")

    return rows, error_log

In [95]:
print(len(raw_key))
print(len(url_key))

20
19

In [96]:
total_key = {**raw_key, **url_key}
repo_data = {k: v for k, v in total_key.items()}

In [97]:
repo_data

{'fork': False,
 'created_at': '2010-08-24T01:37:33Z',
 'updated_at': '2026-04-03T02:14:17Z',
 'pushed_at': '2026-04-03T00:25:12Z',
 'size': 387923,
 'stargazers_count': 48331,
 'forks_count': 19818,
 'subscribers_count': 1105,
 'open_issues_count': 3504,
 'network_count': 19818,
 'has_issues': True,
 'has_projects': True,
 'has_downloads': True,
 'has_wiki': False,
 'has_pages': False,
 'has_discussions': False,
 'archived': False,
 'disabled': False,
 'allow_forking': True,
 'has_pull_requests': True,
 'html_url': 'https://github.com/pandas-dev/pandas',
 'homepage': 'https://pandas.pydata.org',
 'contributors_url': 'https://api.github.com/repos/pandas-dev/pandas/contributors',
 'commits_url': 'https://api.github.com/repos/pandas-dev/pandas/commits{/sha}',
 'issues_url': 'https://api.github.com/repos/pandas-dev/pandas/issues{/number}',
 'issue_comment_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/comments{/number}',
 'pulls_url': 'https://api.github.com/repos/pandas-dev/pandas/pulls{/number}',
 'releases_url': 'https://api.github.com/repos/pandas-dev/pandas/releases{/id}',
 'languages_url': 'https://api.github.com/repos/pandas-dev/pandas/languages',
 'branches_url': 'https://api.github.com/repos/pandas-dev/pandas/branches{/branch}',
 'tags_url': 'https://api.github.com/repos/pandas-dev/pandas/tags',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/events',
 'issue_events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/events{/number}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/comments{/number}',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/labels{/name}',
 'milestones_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones{/number}',
 'deployments_url': 'https://api.github.com/repos/pandas-dev/pandas/deployments',
 'stargazers_url': 'https://api.github.com/repos/pandas-dev/pandas/stargazers',
 'subscribers_url': 'https://api.github.com/repos/pandas-dev/pandas/subscribers'}

In [98]:
flattened_data, error_log = walk_json(repo_data)

[checkpoint] saved 100 rows
[checkpoint] saved 200 rows
[done] total rows=215, total errors=0

In [105]:
df = pd.DataFrame(flattened_data)
df

,path,key,dtype,example_value,is_github_api_url,fetch_status,error_message,depth
0,fork,fork,bool,False,False,None,None,0
1,created_at,created_at,str,2010-08-24T01:37:33Z,False,None,None,0
2,updated_at,updated_at,str,2026-04-03T02:14:17Z,False,None,None,0
3,pushed_at,pushed_at,str,2026-04-03T00:25:12Z,False,None,None,0
4,size,size,int,387923,False,None,None,0
...,...,...,...,...,...,...,...,...
210,subscribers_url.__api__[25],[25],dict,"{'login': 'invinciblejha', 'id': 1061207, 'nod...",False,None,None,1
211,subscribers_url.__api__[26],[26],dict,"{'login': 'stephenwlin', 'id': 2342637, 'node_...",False,None,None,1
212,subscribers_url.__api__[27],[27],dict,"{'login': 'strayhorn', 'id': 3350114, 'node_id...",False,None,None,1
213,subscribers_url.__api__[28],[28],dict,"{'login': 'binaryechoes', 'id': 1815971, 'node...",False,None,None,1
214,subscribers_url.__api__[29],[29],dict,"{'login': 'bkeener', 'id': 1179448, 'node_id':...",False,None,None,1

---

### Nested GitHub API Flatten 결과 정리

---

### 정리 목적

현재 `walk_json`을 통해 flatten한 결과에는 repository 자체의 health를 직접 설명하는 정보와,
nested endpoint에서 파생된 개별 객체 정보가 혼합되어 있다.

최종 목표는 **repository 단위의 health feature table 구성**이므로,
모든 flattened row를 그대로 유지하는 것은 비효율적이다.

따라서 각 데이터는 아래 3가지 기준으로 구분한다.

* 그대로 유지
* 집계 후 사용
* 제거

---

### 최종 분류 기준표

| 데이터 그룹             | 예시 path / 형태                                                        | 처리 방식   | 이유               | 활용 방식              |
| ------------------ | ------------------------------------------------------------------- | ------- | ---------------- | ------------------ |
| Repository root 통계 | stargazers_count, forks_count, subscribers_count, open_issues_count | 유지      | repo-level 정량 정보 | 직접 feature 사용      |
| Repository 상태 flag | has_issues, has_wiki, archived, disabled, allow_forking             | 유지      | 운영 상태 설명         | governance feature |
| 시간 정보              | created_at, updated_at, pushed_at                                   | 유지      | 활동성/신선도 반영       | time-based feature |
| endpoint URL       | contributors_url, languages_url 등                                   | 집계 후 사용 | 추가 데이터 source    | fetch 후 feature 생성 |
| contributor 객체     | contributors_url.**api**[i]                                         | 집계 후 사용 | 개별 user row는 불필요 | 분포/집중도 계산          |
| contributor 프로필    | login, id, avatar_url 등                                             | 제거      | 식별자 수준 정보        | 사용 안 함             |
| language raw       | languages_url.**api**.Python 등                                      | 집계 후 사용 | 언어 구성 의미 있음      | entropy / 비율       |
| tag raw            | tags_url.**api**[i]                                                 | 집계 후 사용 | release 정보 포함    | maturity feature   |
| tag 내부 URL         | zipball_url 등                                                       | 제거      | 다운로드 링크          | 의미 없음              |
| event raw          | events_url.**api**[i]                                               | 집계 후 사용 | 활동 유형 중요         | type count         |
| event actor        | actor.login 등                                                       | 제거      | 개인 식별 정보         | 의미 없음              |
| deployment raw     | deployments_url.**api**[i]                                          | 집계 후 사용 | 존재 여부만 중요        | count/flag         |
| stargazer raw      | stargazers_url.**api**[i]                                           | 제거      | count로 대체 가능     | 제거                 |
| subscriber raw     | subscribers_url.**api**[i]                                          | 제거      | count로 충분        | 제거                 |
| URL/템플릿            | commits_url, contents_url 등                                         | 제거      | navigation용      | 제거                 |
| 식별자                | id, node_id                                                         | 제거      | 의미 없음            | 제거                 |

---

### 그대로 유지해야 하는 데이터

| 유형         | 예시                            | 이유      |
| ---------- | ----------------------------- | ------- |
| popularity | stargazers_count, forks_count | 외부 관심도  |
| activity   | open_issues_count             | 운영 상태   |
| governance | has_issues, has_discussions   | 협업 가능성  |
| status     | archived, disabled            | 프로젝트 상태 |
| time       | created_at, pushed_at         | 유지보수 상태 |

---

### 집계 후 사용해야 하는 데이터

| 그룹           | raw 데이터                  | 이유          | 생성 feature             |
| ------------ | ------------------------ | ----------- | ---------------------- |
| contributors | contributors_url.**api** | 구조 분석 필요    | num_contributors, gini |
| languages    | languages_url.**api**    | 기술 스택 구성    | entropy, top_ratio     |
| tags         | tags_url.**api**         | release 성숙도 | stable_ratio           |
| events       | events_url.**api**       | 협업 활동       | event_ratio            |
| deployments  | deployments_url.**api**  | 배포 여부       | has_deployments        |

---

### 제거 대상 데이터

| 대상         | 예시                      | 이유         |
| ---------- | ----------------------- | ---------- |
| 사용자 정보     | login, avatar_url       | 개인 식별용     |
| 링크         | html_url, followers_url | feature 아님 |
| 다운로드 URL   | zipball_url             | 의미 없음      |
| 템플릿 URL    | commits_url{/sha}       | 구조용        |
| raw 객체 row | **api**[i]              | 단위 불일치     |

---

### 현재 데이터에 대한 직접 판단

| 데이터                         | 처리      |
| --------------------------- | ------- |
| contributors_url.**api**[i] | 제거 + 집계 |
| contributors_url            | 유지      |
| languages_url.**api**       | 집계      |
| tags_url.**api**            | 집계      |
| events_url.**api**          | 집계      |
| deployments_url.**api**     | 집계      |
| stargazers_url.**api**      | 제거      |
| subscribers_url.**api**     | 제거      |

---

### 최종 원칙

| 원칙              | 설명                    |
| --------------- | --------------------- |
| repo 단위 유지      | 1 row = 1 repo        |
| raw → aggregate | 객체 대신 통계              |
| URL 제거          | 링크는 feature 아님        |
| 분포 중심           | count, ratio, entropy |
| 범용성 유지          | 모든 repo에 적용 가능        |

---

### 핵심 결론

> 개별 객체(contributor, event, tag)는 제거하고, repository-level 통계로 변환하여 사용한다.

---

## 불필요한 root / template 제거

In [112]:
DROP_PATHS = [
    # --- URL / LINK ---
    "html_url",
    "homepage",

    # --- TEMPLATE API URL (endpoint 아님, template 형태라 useless) ---
    "commits_url",
    "issues_url",
    "issue_comment_url",
    "pulls_url",
    "releases_url",
    "branches_url",
    "issue_events_url",
    "comments_url",
    "labels_url",
    "milestones_url",

    # --- IDENTIFIER ---
    "id",
    "node_id",
    "gravatar_id",
]

In [113]:
df.shape

(215, 8)

In [114]:
df.head()

,path,key,dtype,example_value,is_github_api_url,fetch_status,error_message,depth
0,fork,fork,bool,False,False,None,None,0
1,created_at,created_at,str,2010-08-24T01:37:33Z,False,None,None,0
2,updated_at,updated_at,str,2026-04-03T02:14:17Z,False,None,None,0
3,pushed_at,pushed_at,str,2026-04-03T00:25:12Z,False,None,None,0
4,size,size,int,387923,False,None,None,0

In [115]:
df2 = df[~df["path"].isin(DROP_PATHS)].copy()

In [116]:
df2.shape

(203, 8)

In [117]:
df2.to_csv("sample/deleted.csv")

## nested -> feature로 변환 -> 제거

### **[Contributors]**

contributors data 형태

[
  {
    "login": "jbrockmendel",
    "id": 8078968,
    "node_id": "MDQ6VXNlcjgwNzg5Njg=",
    "avatar_url": "https://avatars.githubusercontent.com/u/8078968?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jbrockmendel",
    "html_url": "https://github.com/jbrockmendel",
    "followers_url": "https://api.github.com/users/jbrockmendel/followers",
    "following_url": "https://api.github.com/users/jbrockmendel/following{/other_user}",
    "gists_url": "https://api.github.com/users/jbrockmendel/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jbrockmendel/subscriptions",
    "organizations_url": "https://api.github.com/users/jbrockmendel/orgs",
    "repos_url": "https://api.github.com/users/jbrockmendel/repos",
    "events_url": "https://api.github.com/users/jbrockmendel/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jbrockmendel/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false,
    "contributions": 5189
  },...

**=> features to make**

- num_contributors
- total_contributions
- top1_contribution_share
- top5_contribution_share
- contribution_gini
- median_contributions

### **[Languages]**

**=> features to make**
- primary_language_ratio
- top2_ratio
- top3_ratio
- entropy
- minor_lang_ratio

+언어를 그룹화:

| 그룹           | 예시                |
| ------------ | ----------------- |
| main         | Python, C, Java   |
| infra        | Shell, Dockerfile |
| markup       | HTML, CSS         |
| config/build | Meson             |

- infra_ratio
- markup_ratio

- is_monolingual (단일 lan인지)

- compiled_ratio (성능 중심 프로젝트인지)

```
COMPILED_LANGS = [
    "C", "C++", "Rust", "Go", "Java", "Swift"
]
INTERPRETED_LANGS = [
    "Python", "JavaScript", "Ruby", "PHP"
]
SCRIPT_LANGS = [
    "Shell"
]
MARKUP_LANGS = [
    "HTML", "CSS", "XSLT"
]
BUILD_LANGS = [
    "Meson", "Makefile"
]
```

### **[Tags]**
> git/github의 버전 표식

**=> features to make**

* **num_tags**

  * 전체 tag 개수
  * 프로젝트의 릴리즈 이력 규모를 나타냄

* **stable_tag_ratio** (정식 릴리즈 중심 프로젝트인지, 실험 및 개발 단계 비중이 큰지)

  * stable: `v3.0.2`, `v2.3.1`
  * unstable/prerelease: `dev`, `rc`, `alpha`, `beta`
  * 해석:

    * 높음 → 안정적인 릴리즈 중심
    * 낮음 → 개발/실험 단계 비중 큼

* **prerelease_tag_ratio** (개발 중간 단계 태그가 얼마나 많은지)

  * 예: `v3.1.0.dev0`, `v3.0.0rc1`
  * 해석:

    * 높음 → active development 상태
    * 낮음 → 안정화된 프로젝트

* **latest_tag_is_stable**

  * 가장 최신 tag가 stable인지 여부
  * 해석:

    * True → 최근 안정 릴리즈 존재
    * False → 현재 개발 진행 중일 가능성

* **latest_tag_is_prerelease**

  * 최신 tag가 dev/rc/beta인지 여부
  * 해석:

    * True → 아직 release 전 단계
    * False → 안정 버전 상태

* **semver_tag_ratio** (버전 규칙 사용 여부)

  * 예: `vMAJOR.MINOR.PATCH` → `v3.0.2`
  * 해석:

    * 높음 → 버전 관리 체계적
    * 낮음 → 비정형/임의 태그 사용

* **num_major_versions / num_minor_versions** (optional)

  * major: `v1.x.x`, `v2.x.x`, `v3.x.x`
  * 해석:

    * 프로젝트의 진화 단계 추정 가능

### **[Events]**

{
    "id": "8064750007",
    "type": "IssueCommentEvent",
    "actor": {
      "id": 73521240,
      "login": "loryzeta33",
      "display_login": "loryzeta33",
      "gravatar_id": "",
      "url": "https://api.github.com/users/loryzeta33",
      "avatar_url": "https://avatars.githubusercontent.com/u/73521240?"
    },
    "repo": {
      "id": 858127,
      "name": "pandas-dev/pandas",
      "url": "https://api.github.com/repos/pandas-dev/pandas"
    },
    "payload": {
      "action": "created",
      "issue": {
        "url": "https://api.github.com/repos/pandas-dev/pandas/issues/65035",
        "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
        "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/65035/labels{/name}",
        "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/65035/comments",
        "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/65035/events",
        "html_url": "https://github.com/pandas-dev/pandas/pull/65035",
        "id": 4197167934,
        "node_id": "PR_kwDOAA0YD87Prf2m",
        "number": 65035,
        "title": "PERF: Optimize BlockManager metadata operations and dtype inference",
        "user": {
          "login": "loryzeta33",
          "id": 73521240,
          "node_id": "MDQ6VXNlcjczNTIxMjQw",
          "avatar_url": "https://avatars.githubusercontent.com/u/73521240?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/loryzeta33",
          "html_url": "https://github.com/loryzeta33",
          "followers_url": "https://api.github.com/users/loryzeta33/followers",
          "following_url": "https://api.github.com/users/loryzeta33/following{/other_user}",
          "gists_url": "https://api.github.com/users/loryzeta33/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/loryzeta33/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/loryzeta33/subscriptions",
          "organizations_url": "https://api.github.com/users/loryzeta33/orgs",
          "repos_url": "https://api.github.com/users/loryzeta33/repos",
          "events_url": "https://api.github.com/users/loryzeta33/events{/privacy}",
          "received_events_url": "https://api.github.com/users/loryzeta33/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "labels": [

        ],
        "state": "open",
        "locked": false,
        "assignees": [

        ],
        "milestone": null,
        "comments": 2,
        "created_at": "2026-04-02T21:52:58Z",
        "updated_at": "2026-04-03T10:47:53Z",
        "closed_at": null,
        "assignee": null,
        "type": null,
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
          "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/65035",
          "html_url": "https://github.com/pandas-dev/pandas/pull/65035",
          "diff_url": "https://github.com/pandas-dev/pandas/pull/65035.diff",
          "patch_url": "https://github.com/pandas-dev/pandas/pull/65035.patch",
          "merged_at": null
        },
        "body": "- [x] tests added / passed\n- [ ] passes `pre-commit run --all-files`\n\n### What changed?\n\nOptimized several `BlockManager` internal metadata operations that previously allocated intermediate lists, causing unnecessary overhead. This is a pure performance improvement without behavioral changes.\n\n1. **`_consolidate_check`**: Now uses a short-circuiting loop with a `set` rather than a list comprehension followed by a `set()` cast. This reduces an $O(N)$ allocation to an early-exit loop, heavily accelerating fragmented dataframes.\n2. **`get_dtypes`**: Now uses `np.fromiter` with a generator rather than converting a list comprehension to an array.\n3. **`interleaved_dtype`**: Updated to accept iterables, avoiding intermediate list allocations in critical callers (like `fast_xs` and `to_numpy` conversions).\n4. **`find_common_type`**: Removed a redundant `list()` cast in the fast path.\n\n### Benchmark\n\nTested on a severely fragmented `BlockManager` with 1,000 columns (500 float, 500 int) to measure `is_consolidated()` worst-case performance before consolidation:\n\n| Metric | Original | Optimized | Improvement |\n| :--- | :--- | :--- | :--- |\n| **Total time (10k calls)** | 0.9668s | 0.0078s | **~124x faster** |\n| **Average time per call** | 96.68µs | 0.78µs | **~99.2% reduction** |\n",
        "reactions": {
          "url": "https://api.github.com/repos/pandas-dev/pandas/issues/65035/reactions",
          "total_count": 0,
          "+1": 0,
          "-1": 0,
          "laugh": 0,
          "hooray": 0,
          "confused": 0,
          "heart": 0,
          "rocket": 0,
          "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/65035/timeline",
        "performed_via_github_app": null,
        "state_reason": null
      },
      "comment": {
        "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/4182973207",
        "html_url": "https://github.com/pandas-dev/pandas/pull/65035#issuecomment-4182973207",
        "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/65035",
        "id": 4182973207,
        "node_id": "IC_kwDOAA0YD875UxsX",
        "user": {
          "login": "loryzeta33",
          "id": 73521240,
          "node_id": "MDQ6VXNlcjczNTIxMjQw",
          "avatar_url": "https://avatars.githubusercontent.com/u/73521240?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/loryzeta33",
          "html_url": "https://github.com/loryzeta33",
          "followers_url": "https://api.github.com/users/loryzeta33/followers",
          "following_url": "https://api.github.com/users/loryzeta33/following{/other_user}",
          "gists_url": "https://api.github.com/users/loryzeta33/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/loryzeta33/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/loryzeta33/subscriptions",
          "organizations_url": "https://api.github.com/users/loryzeta33/orgs",
          "repos_url": "https://api.github.com/users/loryzeta33/repos",
          "events_url": "https://api.github.com/users/loryzeta33/events{/privacy}",
          "received_events_url": "https://api.github.com/users/loryzeta33/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "created_at": "2026-04-03T10:47:53Z",
        "updated_at": "2026-04-03T10:47:53Z",
        "body": "Thanks for the feedback, @jbrockmendel. I have removed the report and benchmark files as requested.\n\nRegarding the overlap with #64574: While that PR optimizes the consolidation process itself (grouping/merging), this PR focuses on reducing Python-level overhead in metadata accessors like `get_dtypes` and the `interleaved_dtype` inference path. These are 'hot' paths used in construction and indexing (like `fast_xs`) that aren't addressed by the consolidation logic alone. The change to `_consolidate_check` here specifically aims to exit as early as possible before any consolidation logic even needs to be considered.",
        "reactions": {
          "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/4182973207/reactions",
          "total_count": 0,
          "+1": 0,
          "-1": 0,
          "laugh": 0,
          "hooray": 0,
          "confused": 0,
          "heart": 0,
          "rocket": 0,
          "eyes": 0
        },
        "performed_via_github_app": null
      }
    },
    "public": true,
    "created_at": "2026-04-03T10:47:53Z",
    "org": {
      "id": 21206976,
      "login": "pandas-dev",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/pandas-dev",
      "avatar_url": "https://avatars.githubusercontent.com/u/21206976?"
    }
  },

**=> features to make**

* **num_events**

  * 전체 event 개수
  * 최근 활동량 자체를 나타냄
  * 해석:

    * 높음 → 활발한 프로젝트
    * 낮음 → 활동 저조 / 정체 가능성
  * 사용 데이터:

    * 각 이벤트 객체 1개 = 1 event
    * → 전체 리스트 길이 (`len(events)`)

* **num_unique_event_types**

  * 등장한 event type 종류 수
  * 해석:

    * 높음 → 다양한 상호작용 (issue, PR, comment 등)
    * 낮음 → 특정 활동에 치우침
  * 사용 데이터:

    * `event["type"]` 값
    * → set으로 unique 개수 계산

* **IssuesEvent_ratio** (이슈 관리 비중)

  * 전체 event 중 IssuesEvent 비율
  * 해석:

    * 높음 → 이슈 기반 관리 활발
  * 사용 데이터:

    * `event["type"] == "IssuesEvent"` 개수 / 전체 이벤트 수

* **IssueCommentEvent_ratio** (토론/피드백 비중)

  * 전체 event 중 IssueCommentEvent 비율
  * 해석:

    * 높음 → 커뮤니케이션 활발
  * 사용 데이터:

    * `event["type"] == "IssueCommentEvent"` 개수 / 전체 이벤트 수
    * (예: 실제 데이터에서 `"type": "IssueCommentEvent"` 확인됨 )

* **PullRequestEvent_ratio** (코드 기여 흐름)

  * 전체 event 중 PullRequestEvent 비율
  * 해석:

    * 높음 → PR 기반 협업 구조
  * 사용 데이터:

    * `event["type"] == "PullRequestEvent"` 개수 / 전체 이벤트 수

* **PushEvent_ratio** (직접 개발 반영 비중)

  * 전체 event 중 PushEvent 비율
  * 해석:

    * 높음 → core contributor 중심 개발
  * 사용 데이터:

    * `event["type"] == "PushEvent"` 개수 / 전체 이벤트 수

* **WatchEvent_ratio** (외부 관심 비중)

  * 전체 event 중 WatchEvent 비율
  * 해석:

    * 높음 → 사용자 관심 증가
  * 사용 데이터:

    * `event["type"] == "WatchEvent"` 개수 / 전체 이벤트 수

* **ForkEvent_ratio** (재사용/확장 관심 비중)

  * 전체 event 중 ForkEvent 비율
  * 해석:

    * 높음 → 프로젝트 활용 및 확장 활발
  * 사용 데이터:

    * `event["type"] == "ForkEvent"` 개수 / 전체 이벤트 수

* **dominant_event_type**

  * 가장 많이 발생한 event type
  * 해석:

    * 프로젝트의 주요 활동 성격 요약
  * 사용 데이터:

    * `event["type"]` 빈도 카운트 → 최빈값

* **dominant_event_ratio**

  * 가장 많은 event type이 전체에서 차지하는 비율
  * 해석:

    * 높음 → 특정 활동에 집중
    * 낮음 → 다양한 활동 존재
  * 사용 데이터:

    * max(event_type_count) / 전체 이벤트 수

* **event_type_entropy** (활동 다양성)

  * event type 분포의 엔트로피
  * 해석:

    * 높음 → 다양한 활동 균형
    * 낮음 → 특정 활동 편중
  * 사용 데이터:

    * 각 event type 비율 p
    * → `-Σ(p * log p)`

* **has_IssuesEvent / has_PullRequestEvent / has_IssueCommentEvent (optional)**

  * 특정 event 존재 여부 (0/1)
  * 해석:

    * 기능 존재 여부 확인
  * 사용 데이터:

    * `event["type"]` 포함 여부 (set membership)

* **recent_event_density (optional)**

  * 이벤트 발생 밀도 (시간 기반)
  * 해석:

    * 높음 → 매우 활발
    * 낮음 → 느린 개발
  * 사용 데이터:

    * `event["created_at"]`
    * → max - min 시간 차 / 이벤트 수
    * (예: `"created_at": "2026-04-03T10:47:53Z"` 존재 )

### **[Deployments]**
> 이 repo의 특정 코드(ref/sha)를 어떤 환경(environment)에 배포하려고 만든 배포 기록

> deployments 데이터는 repository의 배포 이력과 코드 버전(ref) 기반 운영 여부를 나타내며, 배포 존재 여부, 배포 대상(ref) 다양성, 그리고 최근 배포 시점을 통해 프로젝트의 릴리즈/운영 활성도를 보조적으로 측정할 수 있다.

> deployments는 “얼마나 자주, 어떤 코드 기준으로 배포되고 있는가”를 보는 최소한의 운영 지표다.

**=> features to make**

* **num_deployments**

  * 전체 deployment 개수
  * 프로젝트가 배포 이력을 가지고 있는지, 얼마나 자주 배포되는지의 최소한의 지표
  * 해석:

    * 높음 → 배포 활동 존재
    * 낮음 → 배포 이력 거의 없음
  * 사용 데이터:

    * deployment 객체 개수
    * → 전체 리스트 길이 (`len(deployments)`)

* **has_deployments**

  * deployment 기록 존재 여부 (0/1)
  * 해석:

    * True → 배포 프로세스 존재
    * False → 배포 기록 없음
  * 사용 데이터:

    * deployment 리스트가 비어있는지 여부

* **num_unique_refs**

  * deployment에 사용된 서로 다른 ref 개수
  * (브랜치 또는 태그 기준)
  * 해석:

    * 높음 → 다양한 코드 버전이 배포됨
    * 낮음 → 제한된 ref만 배포됨
  * 사용 데이터:

    * `deployment["ref"]`
    * unique 개수 계산

* **tag_based_deployment_ratio**

  * 전체 deployment 중 tag 기반 배포 비율
  * (예: `ref = v3.0.2`)
  * 해석:

    * 높음 → 릴리즈(버전) 기반 배포 구조
    * 낮음 → 브랜치 기반 배포 중심
  * 사용 데이터:

    * `deployment["ref"]`
    * → `v\d+\.\d+\.\d+` 같은 버전 패턴 여부 판별 후 비율 계산

* **deployment_recency_days**

  * 가장 최근 deployment 기준으로 현재까지 지난 시간 (일 단위)
  * 해석:

    * 낮음 → 최근에도 배포 중 (활성 상태)
    * 높음 → 배포 오래 없음
  * 사용 데이터:

    * `deployment["created_at"]`
    * → 가장 최신 값 기준으로 현재 시각과 차이 계산

**=> features to make**
- **stargazers_count**
    - star 누른 사람 수
    - 대중적 관심도
- **subscribers_count**
    - watch(구독)한 사람 수
    - 지속적 관심도
- **subscribers_to_stars_ratio**
    - subscribers_count / stargazers_count
    - 단순 인기 대비 실제 추적 관심 비율

## endpoint 제거