In [3]:
from data.extract_github_repo import build_repo_dataframe
from features.build_features import build_all_features

df2 = build_repo_dataframe("pandas-dev/pandas")
all_features = build_all_features(df2)
all_features.shape

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

(1, 79)

In [2]:
all_features.columns.tolist()

['num_contributors',
 'total_contributions',
 'top1_contribution_share',
 'top5_contribution_share',
 'contribution_gini',
 'median_contributions',
 'num_deployments',
 'has_deployments',
 'num_unique_refs',
 'tag_based_deployment_ratio',
 'deployment_recency_days',
 'num_events',
 'num_unique_event_types',
 'dominant_event_type',
 'dominant_event_ratio',
 'event_type_entropy',
 'has_IssuesEvent',
 'has_PullRequestEvent',
 'has_IssueCommentEvent',
 'recent_event_density',
 'IssuesEvent_ratio',
 'IssueCommentEvent_ratio',
 'PullRequestEvent_ratio',
 'PushEvent_ratio',
 'WatchEvent_ratio',
 'ForkEvent_ratio',
 'stargazers_count',
 'subscribers_count',
 'subscribers_to_stars_ratio',
 'primary_language_ratio',
 'top2_ratio',
 'top3_ratio',
 'language_entropy',
 'minor_lang_ratio',
 'infra_ratio',
 'markup_ratio',
 'is_monolingual',
 'compiled_ratio',
 'num_tags',
 'stable_tag_ratio',
 'prerelease_tag_ratio',
 'latest_tag_is_stable',
 'latest_tag_is_prerelease',
 'semver_tag_ratio',
 'num_major_versions',
 'num_minor_versions',
 'repo_age_days',
 'last_update_recency_days',
 'last_push_recency_days',
 'update_push_gap_days',
 'repo_size',
 'forks_count',
 'open_issues_count',
 'network_count',
 'has_issues',
 'has_projects',
 'has_downloads',
 'has_wiki',
 'has_pages',
 'has_discussions',
 'archived',
 'disabled',
 'allow_forking',
 'has_pull_requests',
 'forks_to_stars_ratio',
 'open_issues_to_stars_ratio',
 'stars_per_repo_age_day',
 'forks_per_repo_age_day',
 'top1_contribution_ratio',
 'top3_contribution_ratio',
 'contribution_entropy',
 'contributors_to_stars_ratio',
 'tag_release_velocity',
 'interaction_ratio',
 'development_ratio',
 'external_interest_event_ratio',
 'stars_per_size',
 'forks_per_size',
 'issues_per_size']

In [4]:
import pandas as pd
repos = [
    "pandas-dev/pandas",
    "numpy/numpy",
    "scikit-learn/scikit-learn",
    "matplotlib/matplotlib",
    "psf/requests",
    "fastapi/fastapi",
    "django/django",
    "pallets/flask",
]

feature_list = []

for repo in repos:
    print(f"Processing: {repo}")

    try:
        df2 = build_repo_dataframe(repo)
        features = build_all_features(df2)

        features.insert(0, "repo_name", repo)
        feature_list.append(features)

        print(repo, features.shape)

    except Exception as e:
        print(f"Failed: {repo}")
        print(e)

all_repo_features = pd.concat(feature_list, ignore_index=True)

all_repo_features.shape

Processing: pandas-dev/pandas

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

pandas-dev/pandas (1, 80)
Processing: numpy/numpy

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

numpy/numpy (1, 80)
Processing: scikit-learn/scikit-learn

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

scikit-learn/scikit-learn (1, 80)
Processing: matplotlib/matplotlib

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

matplotlib/matplotlib (1, 80)
Processing: psf/requests

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

psf/requests (1, 80)
Processing: fastapi/fastapi

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

fastapi/fastapi (1, 80)
Processing: django/django

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

django/django (1, 80)
Processing: pallets/flask
pallets/flask (1, 80)

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

(8, 80)

In [5]:
all_repo_features.columns.tolist()

['repo_name',
 'num_contributors',
 'total_contributions',
 'top1_contribution_share',
 'top5_contribution_share',
 'contribution_gini',
 'median_contributions',
 'num_deployments',
 'has_deployments',
 'num_unique_refs',
 'tag_based_deployment_ratio',
 'deployment_recency_days',
 'num_events',
 'num_unique_event_types',
 'dominant_event_type',
 'dominant_event_ratio',
 'event_type_entropy',
 'has_IssuesEvent',
 'has_PullRequestEvent',
 'has_IssueCommentEvent',
 'recent_event_density',
 'IssuesEvent_ratio',
 'IssueCommentEvent_ratio',
 'PullRequestEvent_ratio',
 'PushEvent_ratio',
 'WatchEvent_ratio',
 'ForkEvent_ratio',
 'stargazers_count',
 'subscribers_count',
 'subscribers_to_stars_ratio',
 'primary_language_ratio',
 'top2_ratio',
 'top3_ratio',
 'language_entropy',
 'minor_lang_ratio',
 'infra_ratio',
 'markup_ratio',
 'is_monolingual',
 'compiled_ratio',
 'num_tags',
 'stable_tag_ratio',
 'prerelease_tag_ratio',
 'latest_tag_is_stable',
 'latest_tag_is_prerelease',
 'semver_tag_ratio',
 'num_major_versions',
 'num_minor_versions',
 'repo_age_days',
 'last_update_recency_days',
 'last_push_recency_days',
 'update_push_gap_days',
 'repo_size',
 'forks_count',
 'open_issues_count',
 'network_count',
 'has_issues',
 'has_projects',
 'has_downloads',
 'has_wiki',
 'has_pages',
 'has_discussions',
 'archived',
 'disabled',
 'allow_forking',
 'has_pull_requests',
 'forks_to_stars_ratio',
 'open_issues_to_stars_ratio',
 'stars_per_repo_age_day',
 'forks_per_repo_age_day',
 'top1_contribution_ratio',
 'top3_contribution_ratio',
 'contribution_entropy',
 'contributors_to_stars_ratio',
 'tag_release_velocity',
 'interaction_ratio',
 'development_ratio',
 'external_interest_event_ratio',
 'stars_per_size',
 'forks_per_size',
 'issues_per_size']

> repo_name이 추가되었으니 (기존 79개 feature) + (repo_name 1개) = 80개

---

# **Make Dataset (Target=1)**

In [1]:
healthy_repos = [
    # Infra / Cloud / DevOps
    "kubernetes/kubernetes",
    "containerd/containerd",
    "cilium/cilium",
    "envoyproxy/envoy",
    "istio/istio",
    "hashicorp/terraform",
    "prometheus/prometheus",
    "grafana/grafana",
    "argoproj/argo-cd",
    "apache/airflow",
    "apache/spark",
    "apache/kafka",
    "elastic/elasticsearch",
    "opensearch-project/OpenSearch",
    "ClickHouse/ClickHouse",
    "redis/redis",
    "etcd-io/etcd",
    "rook/rook",
    "k3s-io/k3s",
    "helm/helm",
    "cert-manager/cert-manager",
    "fluxcd/flux2",
    "minio/minio",
    "apache/flink",
    "trinoio/trino",
    "apache/hadoop",
    "apache/hive",
    "vitessio/vitess",
    "temporalio/temporal",
    "netdata/netdata",
    "jenkinsci/jenkins",

    # ML / Data
    "scikit-learn/scikit-learn",
    "pytorch/pytorch",
    "tensorflow/tensorflow",
    "huggingface/transformers",
    "pandas-dev/pandas",
    "numpy/numpy",
    "matplotlib/matplotlib",
    "streamlit/streamlit",
    "mlflow/mlflow",
    "feast-dev/feast",
    "ray-project/ray",
    "dask/dask",
    "kedro-org/kedro",
    "PrefectHQ/prefect",
    "dagster-io/dagster",
    "bentoml/BentoML",
    "jina-ai/jina",
    "langchain-ai/langchain",
    "deepspeedai/DeepSpeed",
    "vllm-project/vllm",
    "Lightning-AI/pytorch-lightning",

    # Backend / Web
    "django/django",
    "pallets/flask",
    "fastapi/fastapi",
    "spring-projects/spring-boot",
    "expressjs/express",
    "nestjs/nest",
    "gin-gonic/gin",
    "gorilla/mux",
    "encode/uvicorn",
    "tiangolo/sqlmodel",
    "sqlalchemy/sqlalchemy",
    "prisma/prisma",
    "supabase/supabase",
    "appwrite/appwrite",
    "strapi/strapi",

    # Frontend
    "facebook/react",
    "vuejs/core",
    "angular/angular",
    "sveltejs/svelte",
    "vercel/next.js",
    "nuxt/nuxt",
    "tailwindlabs/tailwindcss",
    "vitejs/vite",
    "webpack/webpack",
    "storybookjs/storybook",
    "electron/electron",
    "tauri-apps/tauri",

    # Systems
    "rust-lang/rust",
    "golang/go",
    "llvm/llvm-project",
    "python/cpython",
    "ziglang/zig",
    "denoland/deno",
    "tokio-rs/tokio",
    "BurntSushi/ripgrep",
    "sharkdp/bat",
    "sharkdp/fd",
    "neovim/neovim",
    "tmux/tmux",
    "git/git",
]

hard_negative_repos = [
    "angular/angular.js",
    "atom/atom",
    "typicode/json-server",
    "ramda/ramda",
    "jashkenas/backbone",
    "meteor/meteor",
    "Semantic-Org/Semantic-UI",
    "chartjs/Chart.js",
    "lodash/lodash",
    "moment/moment",
    "jquery/jquery-mobile",
    "vuejs/vuex",
    "facebook/create-react-app",
    "facebookexperimental/Recoil",
    "apache/incubator-mxnet",
    "bower/bower",
    "request/request",
    "gatsbyjs/gatsby",
    "drone/drone",
    "fabricjs/fabric.js",
    "keras-team/keras",
    "pallets/quart",
    "gruntjs/grunt",
    "gulpjs/gulp",
    "coffeescript/coffeescript",
    "apache/storm",
]

easy_negative_repos = [
    "octocat/Hello-World",
    "torvalds/test-tlb",
    "TheAlgorithms/Python",
    "donnemartin/system-design-primer",
    "EbookFoundation/free-programming-books",
    "public-apis/public-apis",
    "kamranahmedse/developer-roadmap",
    "github/gitignore",
    "sindresorhus/awesome",
    "codecrafters-io/build-your-own-x",
    "firstcontributions/first-contributions",
    "30-seconds/30-seconds-of-code",
    "CyC2018/CS-Notes",
    "jwasham/coding-interview-university",
]

additional_easy_negative_repos = [

    # Tutorial / learning repos
    "tensorflow/examples",
    "pytorch/examples",
    "microsoft/ML-For-Beginners",
    "microsoft/Web-Dev-For-Beginners",
    "google/googletest",
    "ossu/computer-science",
    "freeCodeCamp/freeCodeCamp",
    "trekhleb/javascript-algorithms",

    # Awesome/documentation style
    "avelino/awesome-go",
    "vinta/awesome-python",
    "sindresorhus/awesome-nodejs",
    "Solido/awesome-flutter",
    "prakhar1989/awesome-courses",

    # Collection / aggregation repos
    "996icu/996.ICU",
    "f/awesome-chatgpt-prompts",
    "input-output-hk/essential-cardano",
    "ethereum/EIPs",
    "kubernetes/community",

    # Boilerplate/template repos
    "electron-react-boilerplate/electron-react-boilerplate",
    "vercel/nextjs-subscription-payments",
    "h5bp/html5-boilerplate",
    "cookiecutter/cookiecutter",
    "rails/rails-dev-box",

    # Tiny utilities / toy repos
    "leachim6/hello-world",
    "docker/getting-started",
    "torvalds/linux-stable",
    "githubtraining/hellogitworld",
    "octokit/octokit.rb",

    # Practice / interview / notes
    "yangshun/tech-interview-handbook",
    "Snailclimb/JavaGuide",
    "CyC2018/Interview-Notebook",
    "kdn251/interviews",
    "doocs/leetcode",

    # Dataset / benchmark style
    "huggingface/datasets",
    "paperswithcode/paperswithcode-data",
]

In [ ]:
# import pandas as pd
# from pathlib import Path

# from data.extract_github_repo import build_repo_dataframe
# from features.build_features import build_all_features

# repos = healthy_repos

# output_dir = Path("data/repo/healthy_repos")
# output_dir.mkdir(parents=True, exist_ok=True)

# feature_list = []
# failed_repos = []

# for repo in repos:
#     print(f"\nProcessing: {repo}")

#     try:
#         df2 = build_repo_dataframe(repo)
#         features = build_all_features(df2)

#         features.insert(0, "repo_name", repo)

#         safe_repo_name = repo.replace("/", "__")
#         repo_output_path = output_dir / f"{safe_repo_name}_features.csv"

#         features.to_csv(
#             repo_output_path,
#             index=False,
#             encoding="utf-8-sig"
#         )

#         feature_list.append(features)

#         print(f"Saved: {repo_output_path}")
#         print("Feature shape:", features.shape)

#     except Exception as e:
#         failed_repos.append({
#             "repo_name": repo,
#             "error": str(e)
#         })

#         print(f"Failed: {repo}")
#         print(e)

# if feature_list:
#     all_repo_features = pd.concat(feature_list, ignore_index=True)

#     all_output_path = output_dir / "healthy_repo_features.csv"
#     all_repo_features.to_csv(
#         all_output_path,
#         index=False,
#         encoding="utf-8-sig"
#     )

#     print("\nMerged feature shape:", all_repo_features.shape)
#     print(f"Saved merged file: {all_output_path}")

# else:
#     all_repo_features = pd.DataFrame()
#     print("No features created.")

# if failed_repos:
#     failed_df = pd.DataFrame(failed_repos)

#     failed_output_path = output_dir / "healthy_failed_repos.csv"
#     failed_df.to_csv(
#         failed_output_path,
#         index=False,
#         encoding="utf-8-sig"
#     )

#     print(f"Saved failed repo list: {failed_output_path}")

# all_repo_features.shape

Processing: kubernetes/kubernetes

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/kubernetes__kubernetes_features.csv
Feature shape: (1, 80)

Processing: containerd/containerd

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/containerd__containerd_features.csv
Feature shape: (1, 80)

Processing: cilium/cilium

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/cilium__cilium_features.csv
Feature shape: (1, 80)

Processing: envoyproxy/envoy

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/envoyproxy__envoy_features.csv
Feature shape: (1, 80)

Processing: istio/istio

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/istio__istio_features.csv
Feature shape: (1, 80)

Processing: hashicorp/terraform

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/hashicorp__terraform_features.csv
Feature shape: (1, 80)

Processing: prometheus/prometheus

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/prometheus__prometheus_features.csv
Feature shape: (1, 80)

Processing: grafana/grafana

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/grafana__grafana_features.csv
Feature shape: (1, 80)

Processing: argoproj/argo-cd

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/argoproj__argo-cd_features.csv
Feature shape: (1, 80)

Processing: apache/airflow

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/apache__airflow_features.csv
Feature shape: (1, 80)

Processing: apache/spark

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/apache__spark_features.csv
Feature shape: (1, 80)

Processing: apache/kafka

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/apache__kafka_features.csv
Feature shape: (1, 80)

Processing: elastic/elasticsearch

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/elastic__elasticsearch_features.csv
Feature shape: (1, 80)

Processing: opensearch-project/OpenSearch

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/opensearch-project__OpenSearch_features.csv
Feature shape: (1, 80)

Processing: ClickHouse/ClickHouse

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/ClickHouse__ClickHouse_features.csv
Feature shape: (1, 80)

Processing: redis/redis

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/redis__redis_features.csv
Feature shape: (1, 80)

Processing: etcd-io/etcd

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/etcd-io__etcd_features.csv
Feature shape: (1, 80)

Processing: rook/rook

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/rook__rook_features.csv
Feature shape: (1, 80)

Processing: k3s-io/k3s

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/k3s-io__k3s_features.csv
Feature shape: (1, 80)

Processing: helm/helm

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/helm__helm_features.csv
Feature shape: (1, 80)

Processing: cert-manager/cert-manager

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/cert-manager__cert-manager_features.csv
Feature shape: (1, 80)

Processing: fluxcd/flux2

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/fluxcd__flux2_features.csv
Feature shape: (1, 80)

Processing: minio/minio

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/minio__minio_features.csv
Feature shape: (1, 80)

Processing: apache/flink

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/apache__flink_features.csv
Feature shape: (1, 80)

Processing: trinoio/trino
Failed: trinoio/trino
GitHub API request failed: 404 https://api.github.com/repos/trinoio/trino

Processing: apache/hadoop

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/apache__hadoop_features.csv
Feature shape: (1, 80)

Processing: apache/hive

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/apache__hive_features.csv
Feature shape: (1, 80)

Processing: vitessio/vitess

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/vitessio__vitess_features.csv
Feature shape: (1, 80)

Processing: temporalio/temporal

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/temporalio__temporal_features.csv
Feature shape: (1, 80)

Processing: netdata/netdata

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/netdata__netdata_features.csv
Feature shape: (1, 80)

Processing: jenkinsci/jenkins

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/jenkinsci__jenkins_features.csv
Feature shape: (1, 80)

Processing: scikit-learn/scikit-learn

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/scikit-learn__scikit-learn_features.csv
Feature shape: (1, 80)

Processing: pytorch/pytorch

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/pytorch__pytorch_features.csv
Feature shape: (1, 80)

Processing: tensorflow/tensorflow

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/tensorflow__tensorflow_features.csv
Feature shape: (1, 80)

Processing: huggingface/transformers

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/huggingface__transformers_features.csv
Feature shape: (1, 80)

Processing: pandas-dev/pandas

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/pandas-dev__pandas_features.csv
Feature shape: (1, 80)

Processing: numpy/numpy

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/numpy__numpy_features.csv
Feature shape: (1, 80)

Processing: matplotlib/matplotlib

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/matplotlib__matplotlib_features.csv
Feature shape: (1, 80)

Processing: streamlit/streamlit

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/streamlit__streamlit_features.csv
Feature shape: (1, 80)

Processing: mlflow/mlflow

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/mlflow__mlflow_features.csv
Feature shape: (1, 80)

Processing: feast-dev/feast

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/feast-dev__feast_features.csv
Feature shape: (1, 80)

Processing: ray-project/ray

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/ray-project__ray_features.csv
Feature shape: (1, 80)

Processing: dask/dask

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/dask__dask_features.csv
Feature shape: (1, 80)

Processing: kedro-org/kedro

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/kedro-org__kedro_features.csv
Feature shape: (1, 80)

Processing: PrefectHQ/prefect

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/PrefectHQ__prefect_features.csv
Feature shape: (1, 80)

Processing: dagster-io/dagster

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/dagster-io__dagster_features.csv
Feature shape: (1, 80)

Processing: bentoml/BentoML

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/bentoml__BentoML_features.csv
Feature shape: (1, 80)

Processing: jina-ai/jina

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/jina-ai__jina_features.csv
Feature shape: (1, 80)

Processing: langchain-ai/langchain

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/langchain-ai__langchain_features.csv
Feature shape: (1, 80)

Processing: deepspeedai/DeepSpeed

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/deepspeedai__DeepSpeed_features.csv
Feature shape: (1, 80)

Processing: vllm-project/vllm

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/vllm-project__vllm_features.csv
Feature shape: (1, 80)

Processing: Lightning-AI/pytorch-lightning

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/Lightning-AI__pytorch-lightning_features.csv
Feature shape: (1, 80)

Processing: django/django

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/django__django_features.csv
Feature shape: (1, 80)

Processing: pallets/flask

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/pallets__flask_features.csv
Feature shape: (1, 80)

Processing: fastapi/fastapi

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/fastapi__fastapi_features.csv
Feature shape: (1, 80)

Processing: spring-projects/spring-boot

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/spring-projects__spring-boot_features.csv
Feature shape: (1, 80)

Processing: expressjs/express

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/expressjs__express_features.csv
Feature shape: (1, 80)

Processing: nestjs/nest

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/nestjs__nest_features.csv
Feature shape: (1, 80)

Processing: gin-gonic/gin

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/gin-gonic__gin_features.csv
Feature shape: (1, 80)

Processing: gorilla/mux

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/gorilla__mux_features.csv
Feature shape: (1, 80)

Processing: encode/uvicorn

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/encode__uvicorn_features.csv
Feature shape: (1, 80)

Processing: tiangolo/sqlmodel

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/tiangolo__sqlmodel_features.csv
Feature shape: (1, 80)

Processing: sqlalchemy/sqlalchemy

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/sqlalchemy__sqlalchemy_features.csv
Feature shape: (1, 80)

Processing: prisma/prisma

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/prisma__prisma_features.csv
Feature shape: (1, 80)

Processing: supabase/supabase

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/supabase__supabase_features.csv
Feature shape: (1, 80)

Processing: appwrite/appwrite

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/appwrite__appwrite_features.csv
Feature shape: (1, 80)

Processing: strapi/strapi

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/strapi__strapi_features.csv
Feature shape: (1, 80)

Processing: facebook/react

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/facebook__react_features.csv
Feature shape: (1, 80)

Processing: vuejs/core

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/vuejs__core_features.csv
Feature shape: (1, 80)

Processing: angular/angular

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/angular__angular_features.csv
Feature shape: (1, 80)

Processing: sveltejs/svelte

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/sveltejs__svelte_features.csv
Feature shape: (1, 80)

Processing: vercel/next.js

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/vercel__next.js_features.csv
Feature shape: (1, 80)

Processing: nuxt/nuxt

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/nuxt__nuxt_features.csv
Feature shape: (1, 80)

Processing: tailwindlabs/tailwindcss

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/tailwindlabs__tailwindcss_features.csv
Feature shape: (1, 80)

Processing: vitejs/vite

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/vitejs__vite_features.csv
Feature shape: (1, 80)

Processing: webpack/webpack

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/webpack__webpack_features.csv
Feature shape: (1, 80)

Processing: storybookjs/storybook

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/storybookjs__storybook_features.csv
Feature shape: (1, 80)

Processing: electron/electron

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/electron__electron_features.csv
Feature shape: (1, 80)

Processing: tauri-apps/tauri

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/tauri-apps__tauri_features.csv
Feature shape: (1, 80)

Processing: rust-lang/rust

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/rust-lang__rust_features.csv
Feature shape: (1, 80)

Processing: golang/go

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/golang__go_features.csv
Feature shape: (1, 80)

Processing: llvm/llvm-project

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/llvm__llvm-project_features.csv
Feature shape: (1, 80)

Processing: python/cpython

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/python__cpython_features.csv
Feature shape: (1, 80)

Processing: ziglang/zig

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/ziglang__zig_features.csv
Feature shape: (1, 80)

Processing: denoland/deno

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/denoland__deno_features.csv
Feature shape: (1, 80)

Processing: tokio-rs/tokio

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/tokio-rs__tokio_features.csv
Feature shape: (1, 80)

Processing: BurntSushi/ripgrep

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/BurntSushi__ripgrep_features.csv
Feature shape: (1, 80)

Processing: sharkdp/bat

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/sharkdp__bat_features.csv
Feature shape: (1, 80)

Processing: sharkdp/fd

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/sharkdp__fd_features.csv
Feature shape: (1, 80)

Processing: neovim/neovim

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/neovim__neovim_features.csv
Feature shape: (1, 80)

Processing: tmux/tmux

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/tmux__tmux_features.csv
Feature shape: (1, 80)

Processing: git/git
Saved: data/repo/git__git_features.csv
Feature shape: (1, 80)

Merged feature shape: (91, 80)
Saved merged file: data/repo/healthy_repo_features.csv
Saved failed repo list: data/repo/healthy_failed_repos.csv

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

(91, 80)

In [ ]:
import pandas as pd
from pathlib import Path

from data.extract_github_repo import build_repo_dataframe
from features.build_features import build_all_features

repos = hard_negative_repos + easy_negative_repos + additional_easy_negative_repos

output_dir = Path("data/repo/unhealthy_repos")
output_dir.mkdir(parents=True, exist_ok=True)

feature_list = []
failed_repos = []

for repo in repos:
    print(f"\nProcessing: {repo}")

    try:
        df2 = build_repo_dataframe(repo)
        features = build_all_features(df2)

        features.insert(0, "repo_name", repo)

        safe_repo_name = repo.replace("/", "__")
        repo_output_path = output_dir / f"{safe_repo_name}_features.csv"

        features.to_csv(
            repo_output_path,
            index=False,
            encoding="utf-8-sig"
        )

        feature_list.append(features)

        print(f"Saved: {repo_output_path}")
        print("Feature shape:", features.shape)

    except Exception as e:
        failed_repos.append({
            "repo_name": repo,
            "error": str(e)
        })

        print(f"Failed: {repo}")
        print(e)

if feature_list:
    all_repo_features = pd.concat(feature_list, ignore_index=True)

    all_output_path = output_dir / "healthy_repo_features.csv"
    all_repo_features.to_csv(
        all_output_path,
        index=False,
        encoding="utf-8-sig"
    )

    print("\nMerged feature shape:", all_repo_features.shape)
    print(f"Saved merged file: {all_output_path}")

else:
    all_repo_features = pd.DataFrame()
    print("No features created.")

if failed_repos:
    failed_df = pd.DataFrame(failed_repos)

    failed_output_path = output_dir / "unhealthy_failed_repos.csv"
    failed_df.to_csv(
        failed_output_path,
        index=False,
        encoding="utf-8-sig"
    )

    print(f"Saved failed repo list: {failed_output_path}")

all_repo_features.shape

Processing: angular/angular.js

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/angular__angular.js_features.csv
Feature shape: (1, 80)

Processing: atom/atom

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/atom__atom_features.csv
Feature shape: (1, 80)

Processing: typicode/json-server

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/typicode__json-server_features.csv
Feature shape: (1, 80)

Processing: ramda/ramda

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/ramda__ramda_features.csv
Feature shape: (1, 80)

Processing: jashkenas/backbone

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/jashkenas__backbone_features.csv
Feature shape: (1, 80)

Processing: meteor/meteor

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/meteor__meteor_features.csv
Feature shape: (1, 80)

Processing: Semantic-Org/Semantic-UI

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/Semantic-Org__Semantic-UI_features.csv
Feature shape: (1, 80)

Processing: chartjs/Chart.js

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/chartjs__Chart.js_features.csv
Feature shape: (1, 80)

Processing: lodash/lodash

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/lodash__lodash_features.csv
Feature shape: (1, 80)

Processing: moment/moment

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/moment__moment_features.csv
Feature shape: (1, 80)

Processing: jquery/jquery-mobile

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/jquery__jquery-mobile_features.csv
Feature shape: (1, 80)

Processing: vuejs/vuex

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/vuejs__vuex_features.csv
Feature shape: (1, 80)

Processing: facebook/create-react-app

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/facebook__create-react-app_features.csv
Feature shape: (1, 80)

Processing: facebookexperimental/Recoil

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/facebookexperimental__Recoil_features.csv
Feature shape: (1, 80)

Processing: apache/incubator-mxnet

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/apache__incubator-mxnet_features.csv
Feature shape: (1, 80)

Processing: bower/bower

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/bower__bower_features.csv
Feature shape: (1, 80)

Processing: request/request

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/request__request_features.csv
Feature shape: (1, 80)

Processing: gatsbyjs/gatsby

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/gatsbyjs__gatsby_features.csv
Feature shape: (1, 80)

Processing: drone/drone

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/drone__drone_features.csv
Feature shape: (1, 80)

Processing: fabricjs/fabric.js

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/fabricjs__fabric.js_features.csv
Feature shape: (1, 80)

Processing: keras-team/keras

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/keras-team__keras_features.csv
Feature shape: (1, 80)

Processing: pallets/quart

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/pallets__quart_features.csv
Feature shape: (1, 80)

Processing: gruntjs/grunt

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/gruntjs__grunt_features.csv
Feature shape: (1, 80)

Processing: gulpjs/gulp

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/gulpjs__gulp_features.csv
Feature shape: (1, 80)

Processing: coffeescript/coffeescript
Failed: coffeescript/coffeescript
GitHub API request failed: 404 https://api.github.com/repos/coffeescript/coffeescript

Processing: apache/storm

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/apache__storm_features.csv
Feature shape: (1, 80)

Processing: octocat/Hello-World
Saved: data/repo/healthy_repos/octocat__Hello-World_features.csv
Feature shape: (1, 80)

Processing: torvalds/test-tlb
Saved: data/repo/healthy_repos/torvalds__test-tlb_features.csv
Feature shape: (1, 80)

Processing: TheAlgorithms/Python
Saved: data/repo/healthy_repos/TheAlgorithms__Python_features.csv
Feature shape: (1, 80)

Processing: donnemartin/system-design-primer
Saved: data/repo/healthy_repos/donnemartin__system-design-primer_features.csv
Feature shape: (1, 80)

Processing: EbookFoundation/free-programming-books
Saved: data/repo/healthy_repos/EbookFoundation__free-programming-books_features.csv
Feature shape: (1, 80)

Processing: public-apis/public-apis
Saved: data/repo/healthy_repos/public-apis__public-apis_features.csv
Feature shape: (1, 80)

Processing: kamranahmedse/developer-roadmap

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/kamranahmedse__developer-roadmap_features.csv
Feature shape: (1, 80)

Processing: github/gitignore
Saved: data/repo/healthy_repos/github__gitignore_features.csv
Feature shape: (1, 80)

Processing: sindresorhus/awesome
Saved: data/repo/healthy_repos/sindresorhus__awesome_features.csv
Feature shape: (1, 80)

Processing: codecrafters-io/build-your-own-x
Saved: data/repo/healthy_repos/codecrafters-io__build-your-own-x_features.csv
Feature shape: (1, 80)

Processing: firstcontributions/first-contributions
Saved: data/repo/healthy_repos/firstcontributions__first-contributions_features.csv
Feature shape: (1, 80)

Processing: 30-seconds/30-seconds-of-code

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/30-seconds__30-seconds-of-code_features.csv
Feature shape: (1, 80)

Processing: CyC2018/CS-Notes
Saved: data/repo/healthy_repos/CyC2018__CS-Notes_features.csv
Feature shape: (1, 80)

Processing: jwasham/coding-interview-university
Saved: data/repo/healthy_repos/jwasham__coding-interview-university_features.csv
Feature shape: (1, 80)

Processing: tensorflow/examples

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/tensorflow__examples_features.csv
Feature shape: (1, 80)

Processing: pytorch/examples
Saved: data/repo/healthy_repos/pytorch__examples_features.csv
Feature shape: (1, 80)

Processing: microsoft/ML-For-Beginners
Saved: data/repo/healthy_repos/microsoft__ML-For-Beginners_features.csv
Feature shape: (1, 80)

Processing: microsoft/Web-Dev-For-Beginners
Saved: data/repo/healthy_repos/microsoft__Web-Dev-For-Beginners_features.csv
Feature shape: (1, 80)

Processing: google/googletest

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/google__googletest_features.csv
Feature shape: (1, 80)

Processing: ossu/computer-science

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/ossu__computer-science_features.csv
Feature shape: (1, 80)

Processing: freeCodeCamp/freeCodeCamp
Saved: data/repo/healthy_repos/freeCodeCamp__freeCodeCamp_features.csv
Feature shape: (1, 80)

Processing: trekhleb/javascript-algorithms
Saved: data/repo/healthy_repos/trekhleb__javascript-algorithms_features.csv
Feature shape: (1, 80)

Processing: avelino/awesome-go
Saved: data/repo/healthy_repos/avelino__awesome-go_features.csv
Feature shape: (1, 80)

Processing: vinta/awesome-python
Saved: data/repo/healthy_repos/vinta__awesome-python_features.csv
Feature shape: (1, 80)

Processing: sindresorhus/awesome-nodejs
Saved: data/repo/healthy_repos/sindresorhus__awesome-nodejs_features.csv
Feature shape: (1, 80)

Processing: Solido/awesome-flutter
Saved: data/repo/healthy_repos/Solido__awesome-flutter_features.csv
Feature shape: (1, 80)

Processing: prakhar1989/awesome-courses
Saved: data/repo/healthy_repos/prakhar1989__awesome-courses_features.csv
Feature shape: (1, 80)

Processing: 996icu/996.ICU
Saved: data/repo/healthy_repos/996icu__996.ICU_features.csv
Feature shape: (1, 80)

Processing: f/awesome-chatgpt-prompts
Saved: data/repo/healthy_repos/f__awesome-chatgpt-prompts_features.csv
Feature shape: (1, 80)

Processing: input-output-hk/essential-cardano
Saved: data/repo/healthy_repos/input-output-hk__essential-cardano_features.csv
Feature shape: (1, 80)

Processing: ethereum/EIPs
Saved: data/repo/healthy_repos/ethereum__EIPs_features.csv
Feature shape: (1, 80)

Processing: kubernetes/community
Saved: data/repo/healthy_repos/kubernetes__community_features.csv
Feature shape: (1, 80)

Processing: electron-react-boilerplate/electron-react-boilerplate

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/electron-react-boilerplate__electron-react-boilerplate_features.csv
Feature shape: (1, 80)

Processing: vercel/nextjs-subscription-payments
Saved: data/repo/healthy_repos/vercel__nextjs-subscription-payments_features.csv
Feature shape: (1, 80)

Processing: h5bp/html5-boilerplate

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/h5bp__html5-boilerplate_features.csv
Feature shape: (1, 80)

Processing: cookiecutter/cookiecutter

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/cookiecutter__cookiecutter_features.csv
Feature shape: (1, 80)

Processing: rails/rails-dev-box

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/rails__rails-dev-box_features.csv
Feature shape: (1, 80)

Processing: leachim6/hello-world
Saved: data/repo/healthy_repos/leachim6__hello-world_features.csv
Feature shape: (1, 80)

Processing: docker/getting-started
Saved: data/repo/healthy_repos/docker__getting-started_features.csv
Feature shape: (1, 80)

Processing: torvalds/linux-stable
Failed: torvalds/linux-stable
GitHub API request failed: 404 https://api.github.com/repos/torvalds/linux-stable

Processing: githubtraining/hellogitworld

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/githubtraining__hellogitworld_features.csv
Feature shape: (1, 80)

Processing: octokit/octokit.rb

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/octokit__octokit.rb_features.csv
Feature shape: (1, 80)

Processing: yangshun/tech-interview-handbook

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/yangshun__tech-interview-handbook_features.csv
Feature shape: (1, 80)

Processing: Snailclimb/JavaGuide
Saved: data/repo/healthy_repos/Snailclimb__JavaGuide_features.csv
Feature shape: (1, 80)

Processing: CyC2018/Interview-Notebook
Saved: data/repo/healthy_repos/CyC2018__Interview-Notebook_features.csv
Feature shape: (1, 80)

Processing: kdn251/interviews
Saved: data/repo/healthy_repos/kdn251__interviews_features.csv
Feature shape: (1, 80)

Processing: doocs/leetcode

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/doocs__leetcode_features.csv
Feature shape: (1, 80)

Processing: huggingface/datasets

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/healthy_repos/huggingface__datasets_features.csv
Feature shape: (1, 80)

Processing: paperswithcode/paperswithcode-data
Saved: data/repo/healthy_repos/paperswithcode__paperswithcode-data_features.csv
Feature shape: (1, 80)

Merged feature shape: (73, 80)
Saved merged file: data/repo/healthy_repos/healthy_repo_features.csv
Saved failed repo list: data/repo/healthy_repos/healthy_failed_repos.csv

(73, 80)

In [4]:
import shutil
from pathlib import Path

# 경로 설정
healthy_dir = Path("data/repo/healthy_repos")
unhealthy_dir = Path("data/repo/unhealthy_repos")

unhealthy_dir.mkdir(parents=True, exist_ok=True)

# healthy repo 파일명 set 생성
healthy_filenames = {
    repo.replace("/", "__") + "_features.csv"
    for repo in healthy_repos
}

# 이동 제외 파일
ignore_files = {
    "healthy_repo_features.csv",
    "healthy_failed_repos.csv",
}

moved_files = []

# healthy_repos 폴더 순회
for file_path in healthy_dir.glob("*.csv"):

    file_name = file_path.name

    # merged csv / failed csv 제외
    if file_name in ignore_files:
        continue

    # healthy 목록에 없으면 unhealthy로 이동
    if file_name not in healthy_filenames:

        target_path = unhealthy_dir / file_name

        shutil.move(str(file_path), str(target_path))

        moved_files.append(file_name)

        print(f"Moved: {file_name}")

print("\nDone.")
print(f"Moved file count: {len(moved_files)}")

Moved: yangshun__tech-interview-handbook_features.csv
Moved: CyC2018__Interview-Notebook_features.csv
Moved: octokit__octokit.rb_features.csv
Moved: cookiecutter__cookiecutter_features.csv
Moved: jquery__jquery-mobile_features.csv
Moved: chartjs__Chart.js_features.csv
Moved: microsoft__Web-Dev-For-Beginners_features.csv
Moved: atom__atom_features.csv
Moved: lodash__lodash_features.csv
Moved: pytorch__examples_features.csv
Moved: microsoft__ML-For-Beginners_features.csv
Moved: vinta__awesome-python_features.csv
Moved: public-apis__public-apis_features.csv
Moved: drone__drone_features.csv
Moved: request__request_features.csv
Moved: githubtraining__hellogitworld_features.csv
Moved: ethereum__EIPs_features.csv
Moved: sindresorhus__awesome_features.csv
Moved: angular__angular.js_features.csv
Moved: ossu__computer-science_features.csv
Moved: leachim6__hello-world_features.csv
Moved: meteor__meteor_features.csv
Moved: vercel__nextjs-subscription-payments_features.csv
Moved: apache__incubator-mxnet_features.csv
Moved: gulpjs__gulp_features.csv
Moved: input-output-hk__essential-cardano_features.csv
Moved: prakhar1989__awesome-courses_features.csv
Moved: 30-seconds__30-seconds-of-code_features.csv
Moved: keras-team__keras_features.csv
Moved: CyC2018__CS-Notes_features.csv
Moved: kdn251__interviews_features.csv
Moved: gatsbyjs__gatsby_features.csv
Moved: doocs__leetcode_features.csv
Moved: 996icu__996.ICU_features.csv
Moved: paperswithcode__paperswithcode-data_features.csv
Moved: apache__storm_features.csv
Moved: freeCodeCamp__freeCodeCamp_features.csv
Moved: EbookFoundation__free-programming-books_features.csv
Moved: facebookexperimental__Recoil_features.csv
Moved: Semantic-Org__Semantic-UI_features.csv
Moved: bower__bower_features.csv
Moved: TheAlgorithms__Python_features.csv
Moved: Snailclimb__JavaGuide_features.csv
Moved: moment__moment_features.csv
Moved: donnemartin__system-design-primer_features.csv
Moved: google__googletest_features.csv
Moved: codecrafters-io__build-your-own-x_features.csv
Moved: rails__rails-dev-box_features.csv
Moved: tensorflow__examples_features.csv
Moved: trekhleb__javascript-algorithms_features.csv
Moved: h5bp__html5-boilerplate_features.csv
Moved: jwasham__coding-interview-university_features.csv
Moved: kamranahmedse__developer-roadmap_features.csv
Moved: typicode__json-server_features.csv
Moved: github__gitignore_features.csv
Moved: vuejs__vuex_features.csv
Moved: huggingface__datasets_features.csv
Moved: ramda__ramda_features.csv
Moved: gruntjs__grunt_features.csv
Moved: jashkenas__backbone_features.csv
Moved: facebook__create-react-app_features.csv
Moved: electron-react-boilerplate__electron-react-boilerplate_features.csv
Moved: firstcontributions__first-contributions_features.csv
Moved: kubernetes__community_features.csv
Moved: torvalds__test-tlb_features.csv
Moved: f__awesome-chatgpt-prompts_features.csv
Moved: avelino__awesome-go_features.csv
Moved: pallets__quart_features.csv
Moved: sindresorhus__awesome-nodejs_features.csv
Moved: Solido__awesome-flutter_features.csv
Moved: fabricjs__fabric.js_features.csv
Moved: octocat__Hello-World_features.csv
Moved: docker__getting-started_features.csv

Done.
Moved file count: 73

In [16]:
h_df = []

for i in healthy_dir.glob("*.csv"):
    df = pd.read_csv(i)
    h_df.append(df)

h_df = pd.concat(h_df, ignore_index=True)

In [17]:
type(h_df)

pandas.DataFrame

In [18]:
h_df

,repo_name,num_contributors,total_contributions,top1_contribution_share,top5_contribution_share,contribution_gini,median_contributions,num_deployments,has_deployments,num_unique_refs,...,contribution_entropy,contributors_to_stars_ratio,tag_release_velocity,interaction_ratio,development_ratio,external_interest_event_ratio,stars_per_size,forks_per_size,issues_per_size,error
0,feast-dev/feast,30.0,3139.0,0.173941,0.475948,0.475385,61.5,30.0,1.0,2.0,...,3.005782,0.004283,0.011096,0.100000,0.466667,0.266667,0.027528,0.005168,0.001360,NaN
1,tmux/tmux,19.0,9800.0,0.802143,0.997551,0.923963,2.0,0.0,0.0,0.0,...,0.529017,0.000421,0.007521,0.500000,0.066667,0.366667,2.358165,0.135984,0.002873,NaN
2,etcd-io/etcd,30.0,19115.0,0.229087,0.725556,0.660722,244.0,30.0,1.0,2.0,...,2.523718,0.000581,0.006402,0.566667,0.166667,0.100000,0.536003,0.107205,0.002490,NaN
3,fluxcd/flux2,30.0,3501.0,0.515281,0.844616,0.825545,11.0,30.0,1.0,30.0,...,1.776958,0.003706,0.013621,0.200000,0.400000,0.266667,0.694704,0.064630,0.021372,NaN
4,python/cpython,30.0,85425.0,0.131987,0.409400,0.393314,2052.5,0.0,0.0,0.0,...,3.139422,0.000413,0.008899,0.500000,0.300000,0.000000,0.088486,0.042119,0.011314,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,sharkdp/bat,30.0,2868.0,0.360530,0.736053,0.703254,22.0,30.0,1.0,30.0,...,2.351845,0.000511,0.010216,0.066667,0.100000,0.833333,1.678460,0.044183,0.010231,NaN
162,coffeescript/coffeescript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GitHub API request failed: 404 https://api.git...
163,torvalds/linux-stable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GitHub API request failed: 404 https://api.git...
164,pytorch/pytorch,30.0,33171.0,0.152694,0.444394,0.364006,739.0,30.0,1.0,1.0,...,3.123816,0.000301,0.008444,0.133333,0.500000,0.000000,0.075538,0.020975,0.014103,NaN
165,temporalio/temporal,30.0,7284.0,0.128364,0.472543,0.440783,136.5,1.0,1.0,1.0,...,3.061578,0.001496,0.012536,0.066667,0.133333,0.066667,0.147035,0.011323,0.005185,NaN

In [19]:
u_df = []

for i in unhealthy_dir.glob("*.csv"):
    df = pd.read_csv(i)
    u_df.append(df)

u_df = pd.concat(u_df, ignore_index=True)

In [20]:
u_df

,repo_name,num_contributors,total_contributions,top1_contribution_share,top5_contribution_share,contribution_gini,median_contributions,num_deployments,has_deployments,num_unique_refs,...,top3_contribution_ratio,contribution_entropy,contributors_to_stars_ratio,tag_release_velocity,interaction_ratio,development_ratio,external_interest_event_ratio,stars_per_size,forks_per_size,issues_per_size
0,yangshun/tech-interview-handbook,30,1161.0,0.552972,0.776055,0.784180,4.5,30.0,1.0,30.0,...,0.688200,1.896250,0.000215,0.000278,0.000000,0.000000,1.000000,4.135293,0.491274,0.001304
1,CyC2018/Interview-Notebook,30,3497.0,0.946240,0.958822,0.923868,5.5,30.0,1.0,29.0,...,0.952817,0.386645,0.000163,0.000000,0.000000,0.000000,1.000000,1.586922,0.439064,0.001687
2,octokit/octokit.rb,30,2661.0,0.337091,0.739947,0.723926,18.0,4.0,1.0,4.0,...,0.580985,2.333563,0.007643,0.005000,0.476190,0.238095,0.285714,0.225769,0.066954,0.001438
3,cookiecutter/cookiecutter,30,2525.0,0.387327,0.859802,0.774957,15.5,16.0,1.0,13.0,...,0.689505,2.049365,0.001206,0.006399,0.066667,0.000000,0.933333,7.109746,0.637897,0.082023
4,jquery/jquery-mobile,30,10771.0,0.188562,0.736886,0.722610,69.5,0.0,0.0,0.0,...,0.527156,2.409101,0.003119,0.005241,0.000000,0.000000,1.000000,0.071931,0.017678,0.001361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,sindresorhus/awesome-nodejs,30,474.0,0.744726,0.860759,0.813924,3.0,0.0,0.0,0.0,...,0.833333,1.311147,0.000457,0.000000,0.000000,0.000000,1.000000,42.174583,3.996791,0.016688
69,Solido/awesome-flutter,30,473.0,0.689218,0.773784,0.715927,4.0,30.0,1.0,1.0,...,0.748414,1.629098,0.000500,0.000000,0.000000,0.033333,0.966667,16.931151,1.939334,0.006772
70,fabricjs/fabric.js,30,4830.0,0.414079,0.908075,0.842636,18.5,30.0,1.0,8.0,...,0.845756,1.630235,0.000963,0.005155,0.233333,0.033333,0.733333,0.125760,0.014633,0.001893
71,octocat/Hello-World,3,3.0,0.333333,1.000000,0.000000,1.0,0.0,0.0,0.0,...,1.000000,1.098612,0.000839,0.000000,0.166667,0.000000,0.800000,3575.000000,6157.000000,5863.000000
72,docker/getting-started,30,166.0,0.421687,0.819277,0.744980,1.0,0.0,0.0,0.0,...,0.771084,1.950643,0.009794,0.000000,0.142857,0.000000,0.821429,0.571669,1.191863,0.020903

In [21]:
additional_healthy_repos = [
    # Infra / Cloud / DevOps
    "docker/compose",
    "containerd/nerdctl",
    "open-telemetry/opentelemetry-collector",
    "open-telemetry/opentelemetry-go",
    "open-telemetry/opentelemetry-java",
    "fluent/fluentd",
    "fluent/fluent-bit",
    "argoproj/argo-workflows",
    "crossplane/crossplane",
    "pulumi/pulumi",
    "hashicorp/consul",
    "hashicorp/vault",
    "hashicorp/nomad",
    "grafana/loki",
    "grafana/tempo",
    "jaegertracing/jaeger",
    "linkerd/linkerd2",
    "longhorn/longhorn",
    "openebs/openebs",
    "apache/apisix",

    # Database / Storage / Search
    "mongodb/mongo",
    "postgres/postgres",
    "cockroachdb/cockroach",
    "influxdata/influxdb",
    "timescale/timescaledb",
    "milvus-io/milvus",
    "qdrant/qdrant",
    "weaviate/weaviate",
    "duckdb/duckdb",
    "microsoft/DocumentDB",

    # Data Engineering
    "dbt-labs/dbt-core",
    "apache/beam",
    "apache/iceberg",
    "apache/arrow",
    "apache/parquet-java",
    "delta-io/delta",
    "airbytehq/airbyte",
    "meltano/meltano",
    "great-expectations/great_expectations",
    "DataDog/datadog-agent",

    # ML / AI / Data Science
    "keras-team/keras-core",
    "openai/openai-python",
    "ollama/ollama",
    "ggerganov/llama.cpp",
    "microsoft/LightGBM",
    "dmlc/xgboost",
    "catboost/catboost",
    "optuna/optuna",
    "explosion/spaCy",
    "gensim-developers/gensim",
    "plotly/plotly.py",
    "altair-viz/altair",
    "bokeh/bokeh",
    "gradio-app/gradio",
    "huggingface/diffusers",
    "huggingface/tokenizers",
    "huggingface/accelerate",
    "facebookresearch/faiss",
    "open-mmlab/mmdetection",
    "ultralytics/ultralytics",

    # Backend / API
    "encode/starlette",
    "pydantic/pydantic",
    "psf/requests",
    "aio-libs/aiohttp",
    "celery/celery",
    "apache/superset",
    "getsentry/sentry",
    "tryghost/ghost",
    "rails/rails",
    "laravel/framework",
    "symfony/symfony",
    "nestjs/typeorm",
    "koajs/koa",
    "honojs/hono",
    "elysiajs/elysia",

    # Frontend
    "remix-run/remix",
    "solidjs/solid",
    "preactjs/preact",
    "pmndrs/zustand",
    "reduxjs/redux-toolkit",
    "TanStack/query",
    "TanStack/table",
    "mui/material-ui",
    "chakra-ui/chakra-ui",
    "ant-design/ant-design",
    "shadcn-ui/ui",
    "radix-ui/primitives",
    "storybookjs/storybook",
    "rollup/rollup",
    "parcel-bundler/parcel",

    # Systems / Language / Tools
    "bytecodealliance/wasmtime",
    "WebAssembly/wabt",
    "swc-project/swc",
    "biomejs/biome",
    "denoland/fresh",
    "oven-sh/bun",
    "pnpm/pnpm",
    "yarnpkg/berry",
    "eslint/eslint",
    "prettier/prettier",
    "pytest-dev/pytest",
    "pallets/click",
    "astral-sh/ruff",
    "astral-sh/uv",
    "mitsuhiko/rye",
    "typst/typst",
    "nushell/nushell",
    "starship/starship",
    "wez/wezterm",
    "alacritty/alacritty",
]

In [22]:
additional_unhealthy_repos = [
    # Archived / Deprecated / Maintenance-declined style
    "mozilla/mozjpeg",
    "mozilla/pdf.js",
    "mozilla/bedrock",
    "adobe/brackets",
    "adobe-webplatform/Snap.svg",
    "polymer/polymer",
    "Polymer/polymer",
    "Polymer/lit-element",
    "ampproject/amphtml",
    "googlearchive/android-UniversalMusicPlayer",
    "googlearchive/chromedeveditor",
    "googlearchive/firebase-android-sdk",
    "googlearchive/code-prettify",

    # Old frontend / JS ecosystem
    "emberjs/ember.js",
    "knockout/knockout",
    "knockout/tko",
    "tastejs/todomvc",
    "tastejs/todomvc-app-template",
    "browserify/browserify",
    "substack/node-browserify",
    "componentjs/component",
    "visionmedia/express",
    "visionmedia/debug",
    "visionmedia/superagent",
    "flatiron/flatiron",
    "hapijs/hapi",
    "hapijs/joi",
    "hapijs/boom",
    "hapijs/good",
    "hapijs/inert",
    "hapijs/vision",

    # Old build tools / package managers
    "gruntjs/grunt-contrib-uglify",
    "gruntjs/grunt-contrib-watch",
    "gruntjs/grunt-contrib-cssmin",
    "gulpjs/gulp-util",
    "bower/spec",
    "jamjs/jam",
    "volojs/volo",

    # Old ML / Data / Big Data
    "apache/incubator-predictionio",
    "apache/mahout",
    "apache/sqoop",
    "apache/chukwa",
    "apache/giraph",
    "apache/samza",
    "apache/ambari",
    "apache/oozie",
    "cloudera/hue",
    "twitter/scalding",
    "yahoo/CaffeOnSpark",
    "BVLC/caffe",
    "Theano/Theano",
    "Lasagne/Lasagne",
    "torch/torch7",
    "torch/cutorch",
    "torch/cunn",

    # Old mobile / desktop / misc
    "phonegap/phonegap",
    "phonegap/phonegap-start",
    "apache/cordova-plugin-whitelist",
    "ionic-team/ionic-v1",
    "facebookarchive/nuclide",
    "facebookarchive/watchman",
    "facebookarchive/Keyframes",
    "facebookarchive/rebound",
    "facebookarchive/fixed-data-table",
    "github/choosealicense.com",
    "github/hubot",
    "hubotio/hubot",
    "jekyll/jekyll-admin",
    "middleman/middleman",
]

In [23]:
import pandas as pd
from pathlib import Path

from data.extract_github_repo import build_repo_dataframe
from features.build_features import build_all_features


def build_feature_df_from_repos(repos, output_dir, merged_filename, failed_filename):
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    feature_list = []
    failed_repos = []

    for repo in repos:
        print(f"\nProcessing: {repo}")

        try:
            df2 = build_repo_dataframe(repo)
            features = build_all_features(df2)

            features.insert(0, "repo_name", repo)

            safe_repo_name = repo.replace("/", "__")
            repo_output_path = output_dir / f"{safe_repo_name}_features.csv"

            features.to_csv(
                repo_output_path,
                index=False,
                encoding="utf-8-sig"
            )

            feature_list.append(features)

            print(f"Saved: {repo_output_path}")
            print("Feature shape:", features.shape)

        except Exception as e:
            failed_repos.append({
                "repo_name": repo,
                "error": str(e)
            })

            print(f"Failed: {repo}")
            print(e)

    if feature_list:
        merged_df = pd.concat(feature_list, ignore_index=True)

        all_output_path = output_dir / merged_filename
        merged_df.to_csv(
            all_output_path,
            index=False,
            encoding="utf-8-sig"
        )

        print("\nMerged feature shape:", merged_df.shape)
        print(f"Saved merged file: {all_output_path}")

    else:
        merged_df = pd.DataFrame()
        print("No features created.")

    if failed_repos:
        failed_df = pd.DataFrame(failed_repos)

        failed_output_path = output_dir / failed_filename
        failed_df.to_csv(
            failed_output_path,
            index=False,
            encoding="utf-8-sig"
        )

        print(f"Saved failed repo list: {failed_output_path}")

    return merged_df

In [ ]:
h_df = build_feature_df_from_repos(
    repos=additional_healthy_repos,
    output_dir="data/repo/healthy_repos",
    merged_filename="additional_healthy_repo_features.csv",
    failed_filename="additional_healthy_failed_repos.csv"
)

u_df = build_feature_df_from_repos(
    repos=additional_unhealthy_repos,
    output_dir="data/repo/unhealthy_repos",
    merged_filename="additional_unhealthy_repo_features.csv",
    failed_filename="additional_unhealthy_failed_repos.csv"
)

In [25]:
import pandas as pd
from pathlib import Path

from data.extract_github_repo import build_repo_dataframe
from features.build_features import build_all_features


def resume_build_feature_df_from_repos(
    repos,
    output_dir,
    merged_filename,
    failed_filename
):
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    feature_list = []
    failed_repos = []

    for repo in repos:
        print(f"\nProcessing: {repo}")

        safe_repo_name = repo.replace("/", "__")
        repo_output_path = output_dir / f"{safe_repo_name}_features.csv"

        # 이미 저장된 파일은 건너뛰기
        if repo_output_path.exists():
            print(f"Skip already exists: {repo_output_path}")
            continue

        try:
            df2 = build_repo_dataframe(repo)
            features = build_all_features(df2)

            features.insert(0, "repo_name", repo)

            features.to_csv(
                repo_output_path,
                index=False,
                encoding="utf-8-sig"
            )

            feature_list.append(features)

            print(f"Saved: {repo_output_path}")
            print("Feature shape:", features.shape)

        except Exception as e:
            failed_repos.append({
                "repo_name": repo,
                "error": str(e)
            })

            print(f"Failed: {repo}")
            print(e)

    # 이번에 새로 만든 것만 merge
    if feature_list:
        new_merged_df = pd.concat(feature_list, ignore_index=True)

        new_output_path = output_dir / merged_filename
        new_merged_df.to_csv(
            new_output_path,
            index=False,
            encoding="utf-8-sig"
        )

        print("\nNew merged feature shape:", new_merged_df.shape)
        print(f"Saved new merged file: {new_output_path}")

    else:
        new_merged_df = pd.DataFrame()
        print("No new features created.")

    if failed_repos:
        failed_df = pd.DataFrame(failed_repos)

        failed_output_path = output_dir / failed_filename
        failed_df.to_csv(
            failed_output_path,
            index=False,
            encoding="utf-8-sig"
        )

        print(f"Saved failed repo list: {failed_output_path}")

    return new_merged_df

In [26]:
new_u_df = resume_build_feature_df_from_repos(
    repos=additional_unhealthy_repos,
    output_dir="data/repo/unhealthy_repos",
    merged_filename="additional_unhealthy_repo_features_resume.csv",
    failed_filename="additional_unhealthy_failed_repos_resume.csv"
)

Processing: mozilla/mozjpeg
Skip already exists: data/repo/unhealthy_repos/mozilla__mozjpeg_features.csv

Processing: mozilla/pdf.js
Skip already exists: data/repo/unhealthy_repos/mozilla__pdf.js_features.csv

Processing: mozilla/bedrock

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/mozilla__bedrock_features.csv
Feature shape: (1, 80)

Processing: adobe/brackets

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/adobe__brackets_features.csv
Feature shape: (1, 80)

Processing: adobe-webplatform/Snap.svg

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/adobe-webplatform__Snap.svg_features.csv
Feature shape: (1, 80)

Processing: polymer/polymer

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/polymer__polymer_features.csv
Feature shape: (1, 80)

Processing: Polymer/polymer
Skip already exists: data/repo/unhealthy_repos/Polymer__polymer_features.csv

Processing: Polymer/lit-element

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/Polymer__lit-element_features.csv
Feature shape: (1, 80)

Processing: ampproject/amphtml

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/ampproject__amphtml_features.csv
Feature shape: (1, 80)

Processing: googlearchive/android-UniversalMusicPlayer
Failed: googlearchive/android-UniversalMusicPlayer
GitHub API request failed: 404 https://api.github.com/repos/googlearchive/android-UniversalMusicPlayer

Processing: googlearchive/chromedeveditor

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/googlearchive__chromedeveditor_features.csv
Feature shape: (1, 80)

Processing: googlearchive/firebase-android-sdk
Failed: googlearchive/firebase-android-sdk
GitHub API request failed: 404 https://api.github.com/repos/googlearchive/firebase-android-sdk

Processing: googlearchive/code-prettify

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/googlearchive__code-prettify_features.csv
Feature shape: (1, 80)

Processing: emberjs/ember.js

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/emberjs__ember.js_features.csv
Feature shape: (1, 80)

Processing: knockout/knockout

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/knockout__knockout_features.csv
Feature shape: (1, 80)

Processing: knockout/tko

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/knockout__tko_features.csv
Feature shape: (1, 80)

Processing: tastejs/todomvc

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/tastejs__todomvc_features.csv
Feature shape: (1, 80)

Processing: tastejs/todomvc-app-template
Saved: data/repo/unhealthy_repos/tastejs__todomvc-app-template_features.csv
Feature shape: (1, 80)

Processing: browserify/browserify

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/browserify__browserify_features.csv
Feature shape: (1, 80)

Processing: substack/node-browserify

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/substack__node-browserify_features.csv
Feature shape: (1, 80)

Processing: componentjs/component

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/componentjs__component_features.csv
Feature shape: (1, 80)

Processing: visionmedia/express

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/visionmedia__express_features.csv
Feature shape: (1, 80)

Processing: visionmedia/debug

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/visionmedia__debug_features.csv
Feature shape: (1, 80)

Processing: visionmedia/superagent

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/visionmedia__superagent_features.csv
Feature shape: (1, 80)

Processing: flatiron/flatiron

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/flatiron__flatiron_features.csv
Feature shape: (1, 80)

Processing: hapijs/hapi

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/hapijs__hapi_features.csv
Feature shape: (1, 80)

Processing: hapijs/joi

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/hapijs__joi_features.csv
Feature shape: (1, 80)

Processing: hapijs/boom

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/hapijs__boom_features.csv
Feature shape: (1, 80)

Processing: hapijs/good

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/hapijs__good_features.csv
Feature shape: (1, 80)

Processing: hapijs/inert

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/hapijs__inert_features.csv
Feature shape: (1, 80)

Processing: hapijs/vision

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/hapijs__vision_features.csv
Feature shape: (1, 80)

Processing: gruntjs/grunt-contrib-uglify

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/gruntjs__grunt-contrib-uglify_features.csv
Feature shape: (1, 80)

Processing: gruntjs/grunt-contrib-watch

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/gruntjs__grunt-contrib-watch_features.csv
Feature shape: (1, 80)

Processing: gruntjs/grunt-contrib-cssmin

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/gruntjs__grunt-contrib-cssmin_features.csv
Feature shape: (1, 80)

Processing: gulpjs/gulp-util

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/gulpjs__gulp-util_features.csv
Feature shape: (1, 80)

Processing: bower/spec
Saved: data/repo/unhealthy_repos/bower__spec_features.csv
Feature shape: (1, 80)

Processing: jamjs/jam
Failed: jamjs/jam
GitHub API request failed: 404 https://api.github.com/repos/jamjs/jam

Processing: volojs/volo

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/volojs__volo_features.csv
Feature shape: (1, 80)

Processing: apache/incubator-predictionio

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/apache__incubator-predictionio_features.csv
Feature shape: (1, 80)

Processing: apache/mahout

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/apache__mahout_features.csv
Feature shape: (1, 80)

Processing: apache/sqoop

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/apache__sqoop_features.csv
Feature shape: (1, 80)

Processing: apache/chukwa

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/apache__chukwa_features.csv
Feature shape: (1, 80)

Processing: apache/giraph

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/apache__giraph_features.csv
Feature shape: (1, 80)

Processing: apache/samza

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/apache__samza_features.csv
Feature shape: (1, 80)

Processing: apache/ambari

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/apache__ambari_features.csv
Feature shape: (1, 80)

Processing: apache/oozie

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/apache__oozie_features.csv
Feature shape: (1, 80)

Processing: cloudera/hue

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/cloudera__hue_features.csv
Feature shape: (1, 80)

Processing: twitter/scalding

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/twitter__scalding_features.csv
Feature shape: (1, 80)

Processing: yahoo/CaffeOnSpark
Saved: data/repo/unhealthy_repos/yahoo__CaffeOnSpark_features.csv
Feature shape: (1, 80)

Processing: BVLC/caffe

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/BVLC__caffe_features.csv
Feature shape: (1, 80)

Processing: Theano/Theano

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/Theano__Theano_features.csv
Feature shape: (1, 80)

Processing: Lasagne/Lasagne

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/Lasagne__Lasagne_features.csv
Feature shape: (1, 80)

Processing: torch/torch7
Saved: data/repo/unhealthy_repos/torch__torch7_features.csv
Feature shape: (1, 80)

Processing: torch/cutorch
Saved: data/repo/unhealthy_repos/torch__cutorch_features.csv
Feature shape: (1, 80)

Processing: torch/cunn
Saved: data/repo/unhealthy_repos/torch__cunn_features.csv
Feature shape: (1, 80)

Processing: phonegap/phonegap

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/phonegap__phonegap_features.csv
Feature shape: (1, 80)

Processing: phonegap/phonegap-start

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/phonegap__phonegap-start_features.csv
Feature shape: (1, 80)

Processing: apache/cordova-plugin-whitelist

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/apache__cordova-plugin-whitelist_features.csv
Feature shape: (1, 80)

Processing: ionic-team/ionic-v1
Saved: data/repo/unhealthy_repos/ionic-team__ionic-v1_features.csv
Feature shape: (1, 80)

Processing: facebookarchive/nuclide

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/facebookarchive__nuclide_features.csv
Feature shape: (1, 80)

Processing: facebookarchive/watchman
Failed: facebookarchive/watchman
GitHub API request failed: 404 https://api.github.com/repos/facebookarchive/watchman

Processing: facebookarchive/Keyframes

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/facebookarchive__Keyframes_features.csv
Feature shape: (1, 80)

Processing: facebookarchive/rebound

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/facebookarchive__rebound_features.csv
Feature shape: (1, 80)

Processing: facebookarchive/fixed-data-table

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/facebookarchive__fixed-data-table_features.csv
Feature shape: (1, 80)

Processing: github/choosealicense.com
Saved: data/repo/unhealthy_repos/github__choosealicense.com_features.csv
Feature shape: (1, 80)

Processing: github/hubot

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/github__hubot_features.csv
Feature shape: (1, 80)

Processing: hubotio/hubot

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/hubotio__hubot_features.csv
Feature shape: (1, 80)

Processing: jekyll/jekyll-admin

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

Saved: data/repo/unhealthy_repos/jekyll__jekyll-admin_features.csv
Feature shape: (1, 80)

Processing: middleman/middleman
Saved: data/repo/unhealthy_repos/middleman__middleman_features.csv
Feature shape: (1, 80)

New merged feature shape: (62, 80)
Saved new merged file: data/repo/unhealthy_repos/additional_unhealthy_repo_features_resume.csv
Saved failed repo list: data/repo/unhealthy_repos/additional_unhealthy_failed_repos_resume.csv

/Users/carolyn/Desktop/3-1/opensource/data/oss-health-data/src/features/build_features.py:329: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_prerelease = rows["tag_name"].str.contains(

In [27]:
h_df.shape

(109, 80)

In [33]:
u_df = []

for i in unhealthy_dir.glob("*.csv"):
    df = pd.read_csv(i)
    u_df.append(df)

u_df = pd.concat(u_df, ignore_index=True)

In [34]:
u_df.shape

(137, 80)

In [35]:
h_df = []

for i in healthy_dir.glob("*.csv"):
    df = pd.read_csv(i)
    h_df.append(df)

h_df = pd.concat(h_df, ignore_index=True)

In [36]:
h_df.shape

(274, 81)

In [37]:
h_df.to_csv("h_df.csv")
u_df.to_csv("u_df.csv")

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

h_df["label"] = 1
u_df["label"] = 0

df = pd.concat([h_df, u_df], ignore_index=True)

print(df.shape)

drop_cols = [
    "repo_name",
]

X = df.drop(columns=drop_cols + ["label"], errors="ignore")
y = df["label"]

X = X.select_dtypes(include=[np.number])

print(X.shape)

X = X.fillna(0)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    random_state=42,
    class_weight="balanced"
)

model.fit(X_train, y_train)


y_pred = model.predict(X_test)


print(
    classification_report(
        y_test,
        y_pred,
        target_names=["unhealthy", "healthy"]
    )
)

(411, 82)
(411, 78)
              precision    recall  f1-score   support

   unhealthy       0.53      0.57      0.55        28
     healthy       0.77      0.75      0.76        55

    accuracy                           0.69        83
   macro avg       0.65      0.66      0.66        83
weighted avg       0.69      0.69      0.69        83

In [41]:
importance_df = pd.DataFrame({
    "feature": X.columns,
    "importance": model.feature_importances_
})

importance_df = importance_df.sort_values(
    by="importance",
    ascending=False
)

importance_df.head(20)

                        feature  importance
71         tag_release_velocity    0.070469
48         update_push_gap_days    0.053795
47       last_push_recency_days    0.051684
14           event_type_entropy    0.049429
46     last_update_recency_days    0.033098
12       num_unique_event_types    0.031564
20      IssueCommentEvent_ratio    0.028668
18         recent_event_density    0.027208
5          median_contributions    0.027094
45                repo_age_days    0.023464
51            open_issues_count    0.022958
73            development_ratio    0.022334
63         forks_to_stars_ratio    0.021715
27   subscribers_to_stars_ratio    0.021675
66       forks_per_repo_age_day    0.020339
72            interaction_ratio    0.020198
65       stars_per_repo_age_day    0.019497
1           total_contributions    0.019354
70  contributors_to_stars_ratio    0.017831
25             stargazers_count    0.017497

In [42]:
df.to_csv("dataset.csv")